/**
 * BLASENMERIDIAN (BL) - 67 Punkte
 * Element: Wasser (Yang), Maximalzeit: 15-17 Uhr
 * WHO Standard Acupuncture Point Locations (2008)
 */

import { AcupuncturePoint, calculateHarmonics } from '../meridianPointsDatabase';

export const BLADDER_MERIDIAN: AcupuncturePoint[] = [
  {
    id: 'BL1',
    nameChinese: 'Jingming',
    nameEnglish: 'Bright Eyes',
    nameGerman: 'Helle Augen',
    meridian: 'BL',
    element: 'water',
    location: '0.1 cun über dem inneren Augenwinkel',
    depth: '0.3-0.5 cun entlang der Orbita',
    frequency: 192,
    harmonicFrequencies: calculateHarmonics(192),
    pointTypes: ['regular'],
    functions: ['Erhellt Augen', 'Zerstreut Wind'],
    indications: ['Augenerkrankungen', 'Konjunktivitis', 'Nachtblindheit', 'Tränenfluss'],
    precautions: ['Nicht manipulieren - Blutungsgefahr'],
    chakraCorrespondence: 'ajna'
  },
  {
    id: 'BL2',
    nameChinese: 'Zanzhu',
    nameEnglish: 'Bamboo Gathering',
    nameGerman: 'Bambusansammlung',
    meridian: 'BL',
    element: 'water',
    location: 'Am medialen Augenbrauenende, über BL1',
    depth: '0.3-0.5 cun schräg',
    frequency: 194.5,
    harmonicFrequencies: calculateHarmonics(194.5),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Erhellt Augen', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Augenschmerzen', 'Tränende Augen', 'Schluckauf']
  },
  {
    id: 'BL3',
    nameChinese: 'Meichong',
    nameEnglish: 'Eyebrow Ascension',
    nameGerman: 'Augenbrauenaufstieg',
    meridian: 'BL',
    element: 'water',
    location: '0.5 cun hinter dem vorderen Haaransatz, oberhalb von BL2',
    depth: '0.3-0.5 cun schräg',
    frequency: 197,
    harmonicFrequencies: calculateHarmonics(197),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Schwindel', 'Epilepsie']
  },
  {
    id: 'BL4',
    nameChinese: 'Quchai',
    nameEnglish: 'Deviating Turn',
    nameGerman: 'Abweichende Kurve',
    meridian: 'BL',
    element: 'water',
    location: '0.5 cun hinter dem Haaransatz, 1.5 cun lateral der Mittellinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 199.5,
    harmonicFrequencies: calculateHarmonics(199.5),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Erhellt Augen'],
    indications: ['Kopfschmerzen', 'Verschwommenes Sehen', 'Nasenbluten']
  },
  {
    id: 'BL5',
    nameChinese: 'Wuchu',
    nameEnglish: 'Fifth Place',
    nameGerman: 'Fünfter Platz',
    meridian: 'BL',
    element: 'water',
    location: '1 cun hinter dem Haaransatz, 1.5 cun lateral der Mittellinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 202,
    harmonicFrequencies: calculateHarmonics(202),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Epilepsie', 'Schwindel']
  },
  {
    id: 'BL6',
    nameChinese: 'Chengguang',
    nameEnglish: 'Light Guard',
    nameGerman: 'Lichtwächter',
    meridian: 'BL',
    element: 'water',
    location: '2.5 cun hinter dem Haaransatz, 1.5 cun lateral der Mittellinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 204.5,
    harmonicFrequencies: calculateHarmonics(204.5),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Erhellt Augen'],
    indications: ['Kopfschmerzen', 'Verschwommenes Sehen', 'Nasenprobleme']
  },
  {
    id: 'BL7',
    nameChinese: 'Tongtian',
    nameEnglish: 'Celestial Connection',
    nameGerman: 'Himmlische Verbindung',
    meridian: 'BL',
    element: 'water',
    location: '4 cun hinter dem Haaransatz, 1.5 cun lateral der Mittellinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 207,
    harmonicFrequencies: calculateHarmonics(207),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Öffnet Nase'],
    indications: ['Kopfschmerzen', 'Rhinitis', 'Nasenbluten']
  },
  {
    id: 'BL8',
    nameChinese: 'Luoque',
    nameEnglish: 'Declining Connection',
    nameGerman: 'Abnehmende Verbindung',
    meridian: 'BL',
    element: 'water',
    location: '5.5 cun hinter dem Haaransatz, 1.5 cun lateral der Mittellinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 209.5,
    harmonicFrequencies: calculateHarmonics(209.5),
    pointTypes: ['regular'],
    functions: ['Beruhigt Geist', 'Erhellt Augen'],
    indications: ['Kopfschmerzen', 'Sehstörungen', 'Tinnitus']
  },
  {
    id: 'BL9',
    nameChinese: 'Yuzhen',
    nameEnglish: 'Jade Pillow',
    nameGerman: 'Jadekissen',
    meridian: 'BL',
    element: 'water',
    location: '2.5 cun über dem hinteren Haaransatz, 1.3 cun lateral der Mittellinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 212,
    harmonicFrequencies: calculateHarmonics(212),
    pointTypes: ['regular'],
    functions: ['Erhellt Augen', 'Zerstreut Wind'],
    indications: ['Kopfschmerzen', 'Sehstörungen', 'Nasenprobleme']
  },
  {
    id: 'BL10',
    nameChinese: 'Tianzhu',
    nameEnglish: 'Celestial Pillar',
    nameGerman: 'Himmlische Säule',
    meridian: 'BL',
    element: 'water',
    location: '1.3 cun lateral von DU15, im Trapezius',
    depth: '0.5-1 cun',
    frequency: 214.5,
    harmonicFrequencies: calculateHarmonics(214.5),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Öffnet Sinne', 'Entspannt Sehnen'],
    indications: ['Nackensteifigkeit', 'Kopfschmerzen', 'Schulterschmerzen'],
    chakraCorrespondence: 'vishuddha'
  },
  // Rücken-Shu-Punkte (Transport-Punkte der Organe)
  {
    id: 'BL11',
    nameChinese: 'Dazhu',
    nameEnglish: 'Great Shuttle',
    nameGerman: 'Großes Weberschiffchen',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes T1',
    depth: '0.5-0.8 cun schräg',
    frequency: 217,
    harmonicFrequencies: calculateHarmonics(217),
    pointTypes: ['hui_meeting'],
    functions: ['Stärkt Knochen', 'Zerstreut Wind'],
    indications: ['Nacken- und Rückenschmerzen', 'Husten', 'Fieber']
  },
  {
    id: 'BL12',
    nameChinese: 'Fengmen',
    nameEnglish: 'Wind Gate',
    nameGerman: 'Windtor',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes T2',
    depth: '0.5-0.8 cun schräg',
    frequency: 219.5,
    harmonicFrequencies: calculateHarmonics(219.5),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Öffnet Oberfläche', 'Reguliert Lungen-Qi'],
    indications: ['Erkältung', 'Husten', 'Nackensteifigkeit', 'Rückenschmerzen']
  },
  {
    id: 'BL13',
    nameChinese: 'Feishu',
    nameEnglish: 'Lung Shu',
    nameGerman: 'Lungen-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes T3',
    depth: '0.5-0.8 cun schräg',
    frequency: 222,
    harmonicFrequencies: calculateHarmonics(222),
    pointTypes: ['shu_back'],
    functions: ['Tonisiert Lungen-Qi', 'Nährt Lungen-Yin', 'Klärt Hitze'],
    indications: ['Husten', 'Asthma', 'Tuberkulose', 'Nachtschweiß'],
    chakraCorrespondence: 'anahata'
  },
  {
    id: 'BL14',
    nameChinese: 'Jueyinshu',
    nameEnglish: 'Pericardium Shu',
    nameGerman: 'Perikard-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes T4',
    depth: '0.5-0.8 cun schräg',
    frequency: 224.5,
    harmonicFrequencies: calculateHarmonics(224.5),
    pointTypes: ['shu_back'],
    functions: ['Reguliert Herz-Qi', 'Beruhigt Geist'],
    indications: ['Herzschmerzen', 'Herzklopfen', 'Husten']
  },
  {
    id: 'BL15',
    nameChinese: 'Xinshu',
    nameEnglish: 'Heart Shu',
    nameGerman: 'Herz-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes T5',
    depth: '0.5-0.8 cun schräg',
    frequency: 227,
    harmonicFrequencies: calculateHarmonics(227),
    pointTypes: ['shu_back'],
    functions: ['Tonisiert Herz', 'Beruhigt Geist', 'Nährt Blut'],
    indications: ['Herzschmerzen', 'Schlaflosigkeit', 'Angst', 'Gedächtnisprobleme'],
    chakraCorrespondence: 'anahata'
  },
  {
    id: 'BL17',
    nameChinese: 'Geshu',
    nameEnglish: 'Diaphragm Shu',
    nameGerman: 'Zwerchfell-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes T7',
    depth: '0.5-0.8 cun schräg',
    frequency: 232,
    harmonicFrequencies: calculateHarmonics(232),
    pointTypes: ['shu_back', 'hui_meeting'],
    functions: ['Nährt und belebt Blut', 'Kühlt Blut-Hitze', 'Harmonisiert Zwerchfell'],
    indications: ['Anämie', 'Blutungen', 'Schluckauf', 'Erbrechen'],
    chakraCorrespondence: 'manipura'
  },
  {
    id: 'BL18',
    nameChinese: 'Ganshu',
    nameEnglish: 'Liver Shu',
    nameGerman: 'Leber-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes T9',
    depth: '0.5-0.8 cun schräg',
    frequency: 237,
    harmonicFrequencies: calculateHarmonics(237),
    pointTypes: ['shu_back'],
    functions: ['Reguliert Leber-Qi', 'Erhellt Augen', 'Löst Stagnation'],
    indications: ['Hepatitis', 'Augenkrankheiten', 'Rippenschmerzen', 'Depression']
  },
  {
    id: 'BL19',
    nameChinese: 'Danshu',
    nameEnglish: 'Gallbladder Shu',
    nameGerman: 'Gallenblasen-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes T10',
    depth: '0.5-0.8 cun schräg',
    frequency: 239.5,
    harmonicFrequencies: calculateHarmonics(239.5),
    pointTypes: ['shu_back'],
    functions: ['Reguliert Gallenblasen-Qi', 'Klärt Feuchtigkeit-Hitze'],
    indications: ['Gallenblasenentzündung', 'Bitterer Mundgeschmack', 'Rippenschmerzen']
  },
  {
    id: 'BL20',
    nameChinese: 'Pishu',
    nameEnglish: 'Spleen Shu',
    nameGerman: 'Milz-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes T11',
    depth: '0.5-0.8 cun schräg',
    frequency: 242,
    harmonicFrequencies: calculateHarmonics(242),
    pointTypes: ['shu_back'],
    functions: ['Stärkt Milz', 'Transformiert Feuchtigkeit', 'Nährt Blut'],
    indications: ['Verdauungsprobleme', 'Erschöpfung', 'Ödeme', 'Anämie'],
    chakraCorrespondence: 'manipura'
  },
  {
    id: 'BL21',
    nameChinese: 'Weishu',
    nameEnglish: 'Stomach Shu',
    nameGerman: 'Magen-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes T12',
    depth: '0.5-0.8 cun schräg',
    frequency: 244.5,
    harmonicFrequencies: calculateHarmonics(244.5),
    pointTypes: ['shu_back'],
    functions: ['Harmonisiert Magen', 'Reguliert Qi', 'Löst Stagnation'],
    indications: ['Magenschmerzen', 'Übelkeit', 'Erbrechen', 'Appetitlosigkeit']
  },
  {
    id: 'BL22',
    nameChinese: 'Sanjiaoshu',
    nameEnglish: 'Triple Burner Shu',
    nameGerman: 'Dreifacher Erwärmer-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes L1',
    depth: '0.5-1 cun',
    frequency: 247,
    harmonicFrequencies: calculateHarmonics(247),
    pointTypes: ['shu_back'],
    functions: ['Reguliert Wasserwege', 'Transformiert Feuchtigkeit'],
    indications: ['Ödeme', 'Harnprobleme', 'Verdauungsprobleme']
  },
  {
    id: 'BL23',
    nameChinese: 'Shenshu',
    nameEnglish: 'Kidney Shu',
    nameGerman: 'Nieren-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes L2',
    depth: '0.5-1 cun',
    frequency: 249.5,
    harmonicFrequencies: calculateHarmonics(249.5),
    pointTypes: ['shu_back'],
    functions: ['Tonisiert Nieren', 'Stärkt Rücken', 'Nährt Essenz'],
    indications: ['Lendenschmerzen', 'Impotenz', 'Tinnitus', 'Erschöpfung'],
    chakraCorrespondence: 'svadhisthana'
  },
  {
    id: 'BL25',
    nameChinese: 'Dachangshu',
    nameEnglish: 'Large Intestine Shu',
    nameGerman: 'Dickdarm-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des Dornfortsatzes L4',
    depth: '0.8-1.2 cun',
    frequency: 254.5,
    harmonicFrequencies: calculateHarmonics(254.5),
    pointTypes: ['shu_back'],
    functions: ['Reguliert Dickdarm', 'Stärkt Rücken'],
    indications: ['Lendenschmerzen', 'Durchfall', 'Verstopfung', 'Darmentzündung']
  },
  {
    id: 'BL27',
    nameChinese: 'Xiaochangshu',
    nameEnglish: 'Small Intestine Shu',
    nameGerman: 'Dünndarm-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des 1. Sakralforamens',
    depth: '0.8-1.2 cun',
    frequency: 259.5,
    harmonicFrequencies: calculateHarmonics(259.5),
    pointTypes: ['shu_back'],
    functions: ['Reguliert Dünndarm', 'Trennt klares und trübes'],
    indications: ['Unterbauchschmerzen', 'Harnprobleme', 'Lendenschmerzen']
  },
  {
    id: 'BL28',
    nameChinese: 'Pangguangshu',
    nameEnglish: 'Bladder Shu',
    nameGerman: 'Blasen-Transportpunkt',
    meridian: 'BL',
    element: 'water',
    location: '1.5 cun lateral des 2. Sakralforamens',
    depth: '0.8-1.2 cun',
    frequency: 262,
    harmonicFrequencies: calculateHarmonics(262),
    pointTypes: ['shu_back'],
    functions: ['Reguliert Blase', 'Öffnet Wasserwege'],
    indications: ['Harnprobleme', 'Lendenschmerzen', 'Ischias']
  },
  {
    id: 'BL40',
    nameChinese: 'Weizhong',
    nameEnglish: 'Bend Middle',
    nameGerman: 'Mitte der Beuge',
    meridian: 'BL',
    element: 'water',
    location: 'In der Mitte der Kniekehle, zwischen den Sehnen',
    depth: '1-1.5 cun oder Blutenlassen',
    frequency: 292,
    harmonicFrequencies: calculateHarmonics(292),
    pointTypes: ['he_sea'],
    functions: ['Entspannt Sehnen', 'Aktiviert Kanal', 'Kühlt Blut'],
    indications: ['Lendenschmerzen', 'Knieschmerzen', 'Beinlähmung', 'Hauterkrankungen'],
    chakraCorrespondence: 'muladhara'
  },
  {
    id: 'BL57',
    nameChinese: 'Chengshan',
    nameEnglish: 'Mountain Support',
    nameGerman: 'Bergstütze',
    meridian: 'BL',
    element: 'water',
    location: 'In der Mitte der Wade, am unteren Ende des Gastrocnemius-Muskelbauchs',
    depth: '1-2 cun',
    frequency: 334.5,
    harmonicFrequencies: calculateHarmonics(334.5),
    pointTypes: ['regular'],
    functions: ['Entspannt Sehnen', 'Aktiviert Kanal', 'Lindert Hämorrhoiden'],
    indications: ['Wadenkrämpfe', 'Hämorrhoiden', 'Lendenschmerzen', 'Verstopfung']
  },
  {
    id: 'BL60',
    nameChinese: 'Kunlun',
    nameEnglish: 'Kunlun Mountains',
    nameGerman: 'Kunlun-Gebirge',
    meridian: 'BL',
    element: 'water',
    location: 'Zwischen dem lateralen Malleolus und der Achillessehne',
    depth: '0.5-1 cun',
    frequency: 342,
    harmonicFrequencies: calculateHarmonics(342),
    pointTypes: ['jing_river'],
    functions: ['Zerstreut Wind', 'Entspannt Sehnen', 'Stärkt Rücken'],
    indications: ['Kopfschmerzen', 'Nackensteifigkeit', 'Lendenschmerzen', 'Fersenschmerzen'],
    precautions: ['Kontraindiziert in der Schwangerschaft']
  },
  {
    id: 'BL62',
    nameChinese: 'Shenmai',
    nameEnglish: 'Extending Vessel',
    nameGerman: 'Ausdehnungsgefäß',
    meridian: 'BL',
    element: 'water',
    location: 'In der Vertiefung unter dem lateralen Malleolus',
    depth: '0.3-0.5 cun',
    frequency: 347,
    harmonicFrequencies: calculateHarmonics(347),
    pointTypes: ['confluent'],
    functions: ['Öffnet Yang Qiao Mai', 'Entspannt Sehnen', 'Beruhigt Geist'],
    indications: ['Kopfschmerzen', 'Epilepsie', 'Schlaflosigkeit', 'Knöchelschmerzen'],
    chakraCorrespondence: 'muladhara'
  },
  {
    id: 'BL64',
    nameChinese: 'Jinggu',
    nameEnglish: 'Capital Bone',
    nameGerman: 'Hauptknochen',
    meridian: 'BL',
    element: 'water',
    location: 'Lateral am Fuß, hinter der Tuberositas ossis metatarsalis V',
    depth: '0.3-0.5 cun',
    frequency: 352,
    harmonicFrequencies: calculateHarmonics(352),
    pointTypes: ['yuan_source'],
    functions: ['Klärt Hitze', 'Beruhigt Geist', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Nackensteifigkeit', 'Augenschmerzen', 'Epilepsie']
  },
  {
    id: 'BL65',
    nameChinese: 'Shugu',
    nameEnglish: 'Bone Binder',
    nameGerman: 'Knochenbinder',
    meridian: 'BL',
    element: 'water',
    location: 'Lateral am Fuß, hinter dem 5. MTP-Gelenk',
    depth: '0.3-0.5 cun',
    frequency: 357,
    harmonicFrequencies: calculateHarmonics(357),
    pointTypes: ['shu_stream'],
    functions: ['Klärt Hitze', 'Beruhigt Geist'],
    indications: ['Kopfschmerzen', 'Nackensteifigkeit', 'Sehstörungen']
  },
  {
    id: 'BL66',
    nameChinese: 'Tonggu',
    nameEnglish: 'Foot Connecting Valley',
    nameGerman: 'Verbindungstal des Fußes',
    meridian: 'BL',
    element: 'water',
    location: 'Lateral am 5. Zeh, distal des 5. MTP-Gelenks',
    depth: '0.2-0.3 cun',
    frequency: 362,
    harmonicFrequencies: calculateHarmonics(362),
    pointTypes: ['ying_spring'],
    functions: ['Klärt Hitze', 'Zerstreut Wind'],
    indications: ['Kopfschmerzen', 'Nackensteifigkeit', 'Nasenbluten']
  },
  {
    id: 'BL67',
    nameChinese: 'Zhiyin',
    nameEnglish: 'Reaching Yin',
    nameGerman: 'Yin Erreichen',
    meridian: 'BL',
    element: 'water',
    location: 'Am kleinen Zeh, 0.1 cun lateral des Nagelwinkels',
    depth: '0.1 cun oder Moxibustion',
    frequency: 367,
    harmonicFrequencies: calculateHarmonics(367),
    pointTypes: ['jing_well'],
    functions: ['Korrigiert Fehllagen des Fötus', 'Zerstreut Wind', 'Erhellt Augen'],
    indications: ['Steißlage', 'Kopfschmerzen', 'Augenschmerzen', 'verstopfte Nase']
  }
];
