/**
 * GALLENBLASENMERIDIAN (GB) - 44 Punkte
 * Element: Holz (Yang), Maximalzeit: 23-1 Uhr
 * WHO Standard Acupuncture Point Locations (2008)
 */

import { AcupuncturePoint, calculateHarmonics } from '../meridianPointsDatabase';

export const GALLBLADDER_MERIDIAN: AcupuncturePoint[] = [
  {
    id: 'GB1',
    nameChinese: 'Tongziliao',
    nameEnglish: 'Pupil Bone Hole',
    nameGerman: 'Pupillen-Knochenvertiefung',
    meridian: 'GB',
    element: 'wood',
    location: '0.5 cun lateral des äußeren Augenwinkels',
    depth: '0.3-0.5 cun schräg',
    frequency: 288,
    harmonicFrequencies: calculateHarmonics(288),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind-Hitze', 'Erhellt Augen'],
    indications: ['Augenerkrankungen', 'Kopfschmerzen', 'Gesichtslähmung'],
    chakraCorrespondence: 'ajna'
  },
  {
    id: 'GB2',
    nameChinese: 'Tinghui',
    nameEnglish: 'Auditory Convergence',
    nameGerman: 'Hörvereinigung',
    meridian: 'GB',
    element: 'wood',
    location: 'Vor der Incisura intertragica, bei geöffnetem Mund',
    depth: '0.5-1 cun',
    frequency: 292.4,
    harmonicFrequencies: calculateHarmonics(292.4),
    pointTypes: ['regular'],
    functions: ['Öffnet Ohren', 'Zerstreut Wind-Hitze'],
    indications: ['Tinnitus', 'Schwerhörigkeit', 'Kiefergelenksprobleme', 'Gesichtslähmung']
  },
  {
    id: 'GB3',
    nameChinese: 'Shangguan',
    nameEnglish: 'Upper Gate',
    nameGerman: 'Oberes Tor',
    meridian: 'GB',
    element: 'wood',
    location: 'Oberhalb des Jochbogens, in der Vertiefung vor dem Ohr',
    depth: '0.3-0.5 cun',
    frequency: 296.8,
    harmonicFrequencies: calculateHarmonics(296.8),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Tinnitus', 'Zahnschmerzen', 'Gesichtslähmung']
  },
  {
    id: 'GB4',
    nameChinese: 'Hanyan',
    nameEnglish: 'Jaw Serenity',
    nameGerman: 'Kieferruhe',
    meridian: 'GB',
    element: 'wood',
    location: 'An der Schläfe, am Haaransatz, über der A. temporalis',
    depth: '0.3-0.5 cun schräg',
    frequency: 301.2,
    harmonicFrequencies: calculateHarmonics(301.2),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schmerzen'],
    indications: ['Migräne', 'Schwindel', 'Tinnitus'],
    precautions: ['Vorsicht - A. temporalis']
  },
  {
    id: 'GB5',
    nameChinese: 'Xuanlu',
    nameEnglish: 'Suspended Skull',
    nameGerman: 'Aufgehängter Schädel',
    meridian: 'GB',
    element: 'wood',
    location: 'An der Schläfe, auf halber Strecke zwischen ST8 und GB7',
    depth: '0.3-0.5 cun schräg',
    frequency: 305.6,
    harmonicFrequencies: calculateHarmonics(305.6),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind-Hitze', 'Lindert Schmerzen'],
    indications: ['Migräne', 'Augenrötung', 'Zahnschmerzen']
  },
  {
    id: 'GB8',
    nameChinese: 'Shuaigu',
    nameEnglish: 'Leading Valley',
    nameGerman: 'Führendes Tal',
    meridian: 'GB',
    element: 'wood',
    location: '1.5 cun über der Ohrspitze',
    depth: '0.3-0.5 cun schräg',
    frequency: 318.8,
    harmonicFrequencies: calculateHarmonics(318.8),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Alkoholvergiftung'],
    indications: ['Migräne', 'Übelkeit', 'Erbrechen', 'Kinderkrämpfe']
  },
  {
    id: 'GB14',
    nameChinese: 'Yangbai',
    nameEnglish: 'Yang White',
    nameGerman: 'Yang-Weiß',
    meridian: 'GB',
    element: 'wood',
    location: '1 cun über der Augenbraue, in der Pupillenlinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 345.2,
    harmonicFrequencies: calculateHarmonics(345.2),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Erhellt Augen'],
    indications: ['Kopfschmerzen', 'Augenschmerzen', 'Gesichtslähmung', 'Zucken der Augenlider'],
    chakraCorrespondence: 'ajna'
  },
  {
    id: 'GB20',
    nameChinese: 'Fengchi',
    nameEnglish: 'Wind Pool',
    nameGerman: 'Windteich',
    meridian: 'GB',
    element: 'wood',
    location: 'Unter dem Hinterhaupt, zwischen M. SCM und M. trapezius',
    depth: '0.8-1.2 cun zur Nasenspitze',
    frequency: 371.6,
    harmonicFrequencies: calculateHarmonics(371.6),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Unterdrückt Yang', 'Erhellt Sinne', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Schwindel', 'Erkältung', 'Nackensteifigkeit', 'Hypertonie'],
    chakraCorrespondence: 'ajna'
  },
  {
    id: 'GB21',
    nameChinese: 'Jianjing',
    nameEnglish: 'Shoulder Well',
    nameGerman: 'Schulterbrunnen',
    meridian: 'GB',
    element: 'wood',
    location: 'Auf der Mitte zwischen Akromion und Dornfortsatz C7',
    depth: '0.5-1 cun',
    frequency: 376,
    harmonicFrequencies: calculateHarmonics(376),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Aktiviert Kanal', 'Fördert Laktation'],
    indications: ['Schulterschmerzen', 'Nackensteifigkeit', 'Mastitis', 'verzögerte Geburt'],
    precautions: ['Kontraindiziert in der Schwangerschaft - kann Wehen auslösen'],
    chakraCorrespondence: 'vishuddha'
  },
  {
    id: 'GB24',
    nameChinese: 'Riyue',
    nameEnglish: 'Sun and Moon',
    nameGerman: 'Sonne und Mond',
    meridian: 'GB',
    element: 'wood',
    location: 'Im 7. ICR, auf der Mamillarlinie',
    depth: '0.5-0.8 cun schräg',
    frequency: 389.2,
    harmonicFrequencies: calculateHarmonics(389.2),
    pointTypes: ['mu_front'],
    functions: ['Reguliert Leber und Gallenblase', 'Harmonisiert Shaoyang'],
    indications: ['Gallenblasenentzündung', 'Rippenschmerzen', 'Erbrechen', 'bitterer Mundgeschmack'],
    precautions: ['Nicht tief stechen']
  },
  {
    id: 'GB25',
    nameChinese: 'Jingmen',
    nameEnglish: 'Capital Gate',
    nameGerman: 'Hauptstadttor',
    meridian: 'GB',
    element: 'wood',
    location: 'An der Spitze der 12. Rippe',
    depth: '0.5-1 cun',
    frequency: 393.6,
    harmonicFrequencies: calculateHarmonics(393.6),
    pointTypes: ['mu_front'],
    functions: ['Stärkt Nieren', 'Reguliert Wasserwege'],
    indications: ['Lendenschmerzen', 'Harnprobleme', 'Rippenschmerzen']
  },
  {
    id: 'GB26',
    nameChinese: 'Daimai',
    nameEnglish: 'Girdling Vessel',
    nameGerman: 'Gürtelgefäß',
    meridian: 'GB',
    element: 'wood',
    location: 'Auf der Höhe des Nabels, unter LR13',
    depth: '0.5-1 cun',
    frequency: 398,
    harmonicFrequencies: calculateHarmonics(398),
    pointTypes: ['regular'],
    functions: ['Reguliert Dai Mai', 'Reguliert Menstruation'],
    indications: ['Menstruationsstörungen', 'Leukorr', 'Lendenschmerzen', 'Hernie']
  },
  {
    id: 'GB30',
    nameChinese: 'Huantiao',
    nameEnglish: 'Jumping Circle',
    nameGerman: 'Springender Kreis',
    meridian: 'GB',
    element: 'wood',
    location: 'Am Gesäß, am Schnittpunkt des lateralen und mittleren Drittels zwischen Trochanter major und Hiatus sacralis',
    depth: '2-3 cun',
    frequency: 415.6,
    harmonicFrequencies: calculateHarmonics(415.6),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind-Feuchtigkeit', 'Stärkt Lendenbereich und Beine'],
    indications: ['Ischias', 'Hüftschmerzen', 'Beinlähmung', 'Hauterkrankungen'],
    chakraCorrespondence: 'muladhara'
  },
  {
    id: 'GB31',
    nameChinese: 'Fengshi',
    nameEnglish: 'Wind Market',
    nameGerman: 'Windmarkt',
    meridian: 'GB',
    element: 'wood',
    location: 'Lateral am Oberschenkel, wo die Mittelfingerspitze bei herabhängendem Arm endet',
    depth: '1-2 cun',
    frequency: 420,
    harmonicFrequencies: calculateHarmonics(420),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Juckreiz'],
    indications: ['Beinschmerzen', 'Lähmung', 'Urtikaria', 'Pruritus']
  },
  {
    id: 'GB34',
    nameChinese: 'Yanglingquan',
    nameEnglish: 'Yang Mound Spring',
    nameGerman: 'Yang-Hügel-Quelle',
    meridian: 'GB',
    element: 'wood',
    location: 'In der Vertiefung vor und unter dem Fibulaköpfchen',
    depth: '1-1.5 cun',
    frequency: 433.2,
    harmonicFrequencies: calculateHarmonics(433.2),
    pointTypes: ['he_sea', 'hui_meeting'],
    functions: ['Entspannt Sehnen', 'Reguliert Leber und Gallenblase', 'Zerstreut Feuchtigkeit'],
    indications: ['Knieschmerzen', 'Rippenschmerzen', 'Beinlähmung', 'Gallenblasenerkrankungen'],
    chakraCorrespondence: 'manipura'
  },
  {
    id: 'GB37',
    nameChinese: 'Guangming',
    nameEnglish: 'Bright Light',
    nameGerman: 'Helles Licht',
    meridian: 'GB',
    element: 'wood',
    location: '5 cun über dem Außenknöchel, am Vorderrand der Fibula',
    depth: '0.5-1 cun',
    frequency: 446.4,
    harmonicFrequencies: calculateHarmonics(446.4),
    pointTypes: ['luo_connecting'],
    functions: ['Erhellt Augen', 'Zerstreut Wind-Hitze'],
    indications: ['Augenerkrankungen', 'Nachtblindheit', 'Brustschmerzen', 'Unterschenkelschmerzen'],
    chakraCorrespondence: 'ajna'
  },
  {
    id: 'GB38',
    nameChinese: 'Yangfu',
    nameEnglish: 'Yang Assistance',
    nameGerman: 'Yang-Hilfe',
    meridian: 'GB',
    element: 'wood',
    location: '4 cun über dem Außenknöchel, am Vorderrand der Fibula',
    depth: '0.5-1 cun',
    frequency: 450.8,
    harmonicFrequencies: calculateHarmonics(450.8),
    pointTypes: ['jing_river'],
    functions: ['Zerstreut Wind-Hitze', 'Aktiviert Kanal'],
    indications: ['Migräne', 'Augenaußenwinkelschmerzen', 'Knöchelschmerzen']
  },
  {
    id: 'GB39',
    nameChinese: 'Xuanzhong',
    nameEnglish: 'Suspended Bell',
    nameGerman: 'Aufgehängte Glocke',
    meridian: 'GB',
    element: 'wood',
    location: '3 cun über dem Außenknöchel, am Hinterrand der Fibula',
    depth: '0.5-1 cun',
    frequency: 455.2,
    harmonicFrequencies: calculateHarmonics(455.2),
    pointTypes: ['hui_meeting'],
    functions: ['Nährt Mark', 'Stärkt Knochen', 'Aktiviert Kanal'],
    indications: ['Nackenschmerzen', 'Knöchelschmerzen', 'Knochenerkrankungen', 'Hemiplegie']
  },
  {
    id: 'GB40',
    nameChinese: 'Qiuxu',
    nameEnglish: 'Hill Ruins',
    nameGerman: 'Hügelruinen',
    meridian: 'GB',
    element: 'wood',
    location: 'Vor und unter dem Außenknöchel, in der Vertiefung lateral der Sehne',
    depth: '0.5-1 cun',
    frequency: 459.6,
    harmonicFrequencies: calculateHarmonics(459.6),
    pointTypes: ['yuan_source'],
    functions: ['Reguliert Leber und Gallenblase', 'Aktiviert Kanal'],
    indications: ['Knöchelschmerzen', 'Rippenschmerzen', 'bitterer Mundgeschmack', 'Gallenblasenerkrankungen']
  },
  {
    id: 'GB41',
    nameChinese: 'Foot Linqi',
    nameEnglish: 'Foot Overlooking Tears',
    nameGerman: 'Fußtränenübersicht',
    meridian: 'GB',
    element: 'wood',
    location: 'Auf dem Fußrücken, proximal des 4. und 5. Metatarsale',
    depth: '0.3-0.5 cun',
    frequency: 464,
    harmonicFrequencies: calculateHarmonics(464),
    pointTypes: ['shu_stream', 'confluent'],
    functions: ['Öffnet Dai Mai', 'Reguliert Leber-Qi', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Augenrötung', 'Brustschmerzen', 'Menstruationsstörungen'],
    chakraCorrespondence: 'svadhisthana'
  },
  {
    id: 'GB42',
    nameChinese: 'Diwuhui',
    nameEnglish: 'Earth Fivefold Convergence',
    nameGerman: 'Fünffache Erdenvereinigung',
    meridian: 'GB',
    element: 'wood',
    location: 'Zwischen 4. und 5. Metatarsale, distal von GB41',
    depth: '0.3-0.5 cun',
    frequency: 468.4,
    harmonicFrequencies: calculateHarmonics(468.4),
    pointTypes: ['regular'],
    functions: ['Reguliert Qi', 'Lindert Schwellung'],
    indications: ['Mastitis', 'Augenrötung', 'Fußrückenschmerzen']
  },
  {
    id: 'GB43',
    nameChinese: 'Xiaxi',
    nameEnglish: 'Pinched Ravine',
    nameGerman: 'Eingeklemmte Schlucht',
    meridian: 'GB',
    element: 'wood',
    location: 'Zwischen 4. und 5. Zehe, proximal des Schwimmhautrandes',
    depth: '0.3-0.5 cun',
    frequency: 472.8,
    harmonicFrequencies: calculateHarmonics(472.8),
    pointTypes: ['ying_spring'],
    functions: ['Klärt Hitze', 'Zerstreut Wind'],
    indications: ['Kopfschmerzen', 'Schwindel', 'Tinnitus', 'Brustschmerzen']
  },
  {
    id: 'GB44',
    nameChinese: 'Foot Qiaoyin',
    nameEnglish: 'Foot Yin Portals',
    nameGerman: 'Fußyinportale',
    meridian: 'GB',
    element: 'wood',
    location: 'Am 4. Zeh, 0.1 cun lateral des Nagelwinkels',
    depth: '0.1 cun oder Blutenlassen',
    frequency: 477.2,
    harmonicFrequencies: calculateHarmonics(477.2),
    pointTypes: ['jing_well'],
    functions: ['Klärt Hitze', 'Unterdrückt Yang', 'Beruhigt Geist'],
    indications: ['Kopfschmerzen', 'Tinnitus', 'Schlaflosigkeit', 'Rippenschmerzen']
  }
];
