/**
 * GALLENBLASENMERIDIAN (GB) - 44 Punkte (vollständig)
 * Element: Holz (Yang), Maximalzeit: 23-1 Uhr
 * WHO Standard Acupuncture Point Locations (2008)
 */

import { AcupuncturePoint, calculateHarmonics } from '../meridianPointsDatabase';

export const GALLBLADDER_MERIDIAN: AcupuncturePoint[] = [
  // ========== KOPF-PUNKTE (GB1-GB23) ==========
  {
    id: 'GB1',
    nameChinese: 'Tongziliao',
    nameEnglish: 'Pupil Bone Hole',
    nameGerman: 'Pupillen-Knochenvertiefung',
    meridian: 'GB',
    element: 'wood',
    location: '0.5 cun lateral des äußeren Augenwinkels',
    depth: '0.3-0.5 cun schräg',
    frequency: 288,
    harmonicFrequencies: calculateHarmonics(288),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind-Hitze', 'Erhellt Augen'],
    indications: ['Augenerkrankungen', 'Kopfschmerzen', 'Gesichtslähmung'],
    chakraCorrespondence: 'ajna'
  },
  {
    id: 'GB2',
    nameChinese: 'Tinghui',
    nameEnglish: 'Auditory Convergence',
    nameGerman: 'Hörvereinigung',
    meridian: 'GB',
    element: 'wood',
    location: 'Vor der Incisura intertragica, bei geöffnetem Mund',
    depth: '0.5-1 cun',
    frequency: 292.4,
    harmonicFrequencies: calculateHarmonics(292.4),
    pointTypes: ['regular'],
    functions: ['Öffnet Ohren', 'Zerstreut Wind-Hitze'],
    indications: ['Tinnitus', 'Schwerhörigkeit', 'Kiefergelenksprobleme', 'Gesichtslähmung']
  },
  {
    id: 'GB3',
    nameChinese: 'Shangguan',
    nameEnglish: 'Upper Gate',
    nameGerman: 'Oberes Tor',
    meridian: 'GB',
    element: 'wood',
    location: 'Oberhalb des Jochbogens, in der Vertiefung vor dem Ohr',
    depth: '0.3-0.5 cun',
    frequency: 296.8,
    harmonicFrequencies: calculateHarmonics(296.8),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Tinnitus', 'Zahnschmerzen', 'Gesichtslähmung']
  },
  {
    id: 'GB4',
    nameChinese: 'Hanyan',
    nameEnglish: 'Jaw Serenity',
    nameGerman: 'Kieferruhe',
    meridian: 'GB',
    element: 'wood',
    location: 'An der Schläfe, am Haaransatz, über der A. temporalis',
    depth: '0.3-0.5 cun schräg',
    frequency: 301.2,
    harmonicFrequencies: calculateHarmonics(301.2),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schmerzen'],
    indications: ['Migräne', 'Schwindel', 'Tinnitus'],
    precautions: ['Vorsicht - A. temporalis']
  },
  {
    id: 'GB5',
    nameChinese: 'Xuanlu',
    nameEnglish: 'Suspended Skull',
    nameGerman: 'Aufgehängter Schädel',
    meridian: 'GB',
    element: 'wood',
    location: 'An der Schläfe, auf halber Strecke zwischen ST8 und GB7',
    depth: '0.3-0.5 cun schräg',
    frequency: 305.6,
    harmonicFrequencies: calculateHarmonics(305.6),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind-Hitze', 'Lindert Schmerzen'],
    indications: ['Migräne', 'Augenrötung', 'Zahnschmerzen']
  },
  {
    id: 'GB6',
    nameChinese: 'Xuanli',
    nameEnglish: 'Suspended Tuft',
    nameGerman: 'Aufgehängter Büschel',
    meridian: 'GB',
    element: 'wood',
    location: 'An der Schläfe, auf der Verbindung GB4-GB7',
    depth: '0.3-0.5 cun schräg',
    frequency: 310,
    harmonicFrequencies: calculateHarmonics(310),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schmerzen'],
    indications: ['Migräne', 'Augenrötung', 'Tinnitus']
  },
  {
    id: 'GB7',
    nameChinese: 'Qubin',
    nameEnglish: 'Temporal Hairline Curve',
    nameGerman: 'Schläfenhaaransatzkurve',
    meridian: 'GB',
    element: 'wood',
    location: 'An der Schläfe, auf der Horizontalen durch die Ohrspitze',
    depth: '0.3-0.5 cun schräg',
    frequency: 314.4,
    harmonicFrequencies: calculateHarmonics(314.4),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Kiefergelenksprobleme', 'Schwellung der Wange']
  },
  {
    id: 'GB8',
    nameChinese: 'Shuaigu',
    nameEnglish: 'Leading Valley',
    nameGerman: 'Führendes Tal',
    meridian: 'GB',
    element: 'wood',
    location: '1.5 cun über der Ohrspitze',
    depth: '0.3-0.5 cun schräg',
    frequency: 318.8,
    harmonicFrequencies: calculateHarmonics(318.8),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Alkoholvergiftung'],
    indications: ['Migräne', 'Übelkeit', 'Erbrechen', 'Kinderkrämpfe']
  },
  {
    id: 'GB9',
    nameChinese: 'Tianchong',
    nameEnglish: 'Celestial Hub',
    nameGerman: 'Himmlische Nabe',
    meridian: 'GB',
    element: 'wood',
    location: '0.5 cun posterior zu GB8',
    depth: '0.3-0.5 cun schräg',
    frequency: 323.2,
    harmonicFrequencies: calculateHarmonics(323.2),
    pointTypes: ['regular'],
    functions: ['Beruhigt Geist', 'Lindert Krämpfe'],
    indications: ['Epilepsie', 'Kopfschmerzen', 'Zahnfleischschwellung']
  },
  {
    id: 'GB10',
    nameChinese: 'Fubai',
    nameEnglish: 'Floating White',
    nameGerman: 'Schwebendes Weiß',
    meridian: 'GB',
    element: 'wood',
    location: 'Posterior und inferior zu GB9, an der Haargrenze',
    depth: '0.3-0.5 cun schräg',
    frequency: 327.6,
    harmonicFrequencies: calculateHarmonics(327.6),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Öffnet Ohren'],
    indications: ['Kopfschmerzen', 'Tinnitus', 'Schwerhörigkeit']
  },
  {
    id: 'GB11',
    nameChinese: 'Head Qiaoyin',
    nameEnglish: 'Head Orifice Yin',
    nameGerman: 'Kopf-Öffnungs-Yin',
    meridian: 'GB',
    element: 'wood',
    location: 'Zwischen GB10 und GB12, an der Haargrenze',
    depth: '0.3-0.5 cun schräg',
    frequency: 332,
    harmonicFrequencies: calculateHarmonics(332),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Öffnet Ohren'],
    indications: ['Kopfschmerzen', 'Tinnitus', 'Ohrenschmerzen']
  },
  {
    id: 'GB12',
    nameChinese: 'Wangu',
    nameEnglish: 'Mastoid Process',
    nameGerman: 'Warzenfortsatz',
    meridian: 'GB',
    element: 'wood',
    location: 'In der Vertiefung posteroinferior zum Processus mastoideus',
    depth: '0.5-0.8 cun',
    frequency: 336.4,
    harmonicFrequencies: calculateHarmonics(336.4),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Beruhigt Geist'],
    indications: ['Kopfschmerzen', 'Schlaflosigkeit', 'Gesichtslähmung', 'Zahnschmerzen']
  },
  {
    id: 'GB13',
    nameChinese: 'Benshen',
    nameEnglish: 'Root Spirit',
    nameGerman: 'Wurzelgeist',
    meridian: 'GB',
    element: 'wood',
    location: '0.5 cun hinter dem Haaransatz, 3 cun lateral der Mittellinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 340.8,
    harmonicFrequencies: calculateHarmonics(340.8),
    pointTypes: ['regular'],
    functions: ['Beruhigt Geist', 'Zerstreut Wind'],
    indications: ['Kopfschmerzen', 'Schwindel', 'Epilepsie', 'Angst'],
    chakraCorrespondence: 'ajna'
  },
  {
    id: 'GB14',
    nameChinese: 'Yangbai',
    nameEnglish: 'Yang White',
    nameGerman: 'Yang-Weiß',
    meridian: 'GB',
    element: 'wood',
    location: '1 cun über der Augenbraue, in der Pupillenlinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 345.2,
    harmonicFrequencies: calculateHarmonics(345.2),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Erhellt Augen'],
    indications: ['Kopfschmerzen', 'Augenschmerzen', 'Gesichtslähmung', 'Zucken der Augenlider'],
    chakraCorrespondence: 'ajna'
  },
  {
    id: 'GB15',
    nameChinese: 'Head Linqi',
    nameEnglish: 'Head Overlooking Tears',
    nameGerman: 'Kopf-Tränenübersicht',
    meridian: 'GB',
    element: 'wood',
    location: '0.5 cun hinter dem Haaransatz, in der Pupillenlinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 349.6,
    harmonicFrequencies: calculateHarmonics(349.6),
    pointTypes: ['regular'],
    functions: ['Erhellt Augen', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Augenerkrankungen', 'verstopfte Nase']
  },
  {
    id: 'GB16',
    nameChinese: 'Muchuang',
    nameEnglish: 'Eye Window',
    nameGerman: 'Augenfenster',
    meridian: 'GB',
    element: 'wood',
    location: '1.5 cun hinter dem Haaransatz, in der Pupillenlinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 354,
    harmonicFrequencies: calculateHarmonics(354),
    pointTypes: ['regular'],
    functions: ['Erhellt Augen', 'Zerstreut Wind'],
    indications: ['Kopfschmerzen', 'Augenrötung', 'Gesichtsschwellung']
  },
  {
    id: 'GB17',
    nameChinese: 'Zhengying',
    nameEnglish: 'Upright Construction',
    nameGerman: 'Aufrechte Konstruktion',
    meridian: 'GB',
    element: 'wood',
    location: '2.5 cun hinter dem Haaransatz, in der Pupillenlinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 358.4,
    harmonicFrequencies: calculateHarmonics(358.4),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Schwindel', 'Zahnschmerzen']
  },
  {
    id: 'GB18',
    nameChinese: 'Chengling',
    nameEnglish: 'Spirit Support',
    nameGerman: 'Geistunterstützung',
    meridian: 'GB',
    element: 'wood',
    location: '4 cun hinter dem Haaransatz, in der Pupillenlinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 362.8,
    harmonicFrequencies: calculateHarmonics(362.8),
    pointTypes: ['regular'],
    functions: ['Beruhigt Geist', 'Öffnet Nase'],
    indications: ['Kopfschmerzen', 'Rhinitis', 'Nasenbluten', 'Asthma']
  },
  {
    id: 'GB19',
    nameChinese: 'Naokong',
    nameEnglish: 'Brain Hollow',
    nameGerman: 'Gehirnhöhle',
    meridian: 'GB',
    element: 'wood',
    location: 'Auf Höhe von DU17, 2.25 cun lateral der Mittellinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 367.2,
    harmonicFrequencies: calculateHarmonics(367.2),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Nackensteifigkeit', 'Schwindel', 'Epilepsie']
  },
  {
    id: 'GB20',
    nameChinese: 'Fengchi',
    nameEnglish: 'Wind Pool',
    nameGerman: 'Windteich',
    meridian: 'GB',
    element: 'wood',
    location: 'Unter dem Hinterhaupt, zwischen M. SCM und M. trapezius',
    depth: '0.8-1.2 cun zur Nasenspitze',
    frequency: 371.6,
    harmonicFrequencies: calculateHarmonics(371.6),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Unterdrückt Yang', 'Erhellt Sinne', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Schwindel', 'Erkältung', 'Nackensteifigkeit', 'Hypertonie'],
    chakraCorrespondence: 'ajna'
  },
  {
    id: 'GB21',
    nameChinese: 'Jianjing',
    nameEnglish: 'Shoulder Well',
    nameGerman: 'Schulterbrunnen',
    meridian: 'GB',
    element: 'wood',
    location: 'Auf der Mitte zwischen Akromion und Dornfortsatz C7',
    depth: '0.5-1 cun',
    frequency: 376,
    harmonicFrequencies: calculateHarmonics(376),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Aktiviert Kanal', 'Fördert Laktation'],
    indications: ['Schulterschmerzen', 'Nackensteifigkeit', 'Mastitis', 'verzögerte Geburt'],
    precautions: ['Kontraindiziert in der Schwangerschaft - kann Wehen auslösen'],
    chakraCorrespondence: 'vishuddha'
  },
  {
    id: 'GB22',
    nameChinese: 'Yuanye',
    nameEnglish: 'Armpit Abyss',
    nameGerman: 'Achselhöhlenabgrund',
    meridian: 'GB',
    element: 'wood',
    location: '3 cun unter der Achselhöhle, auf der mittleren Axillarlinie',
    depth: '0.3-0.5 cun schräg',
    frequency: 380.4,
    harmonicFrequencies: calculateHarmonics(380.4),
    pointTypes: ['regular'],
    functions: ['Reguliert Qi', 'Lindert Schwellung'],
    indications: ['Rippenschmerzen', 'Armschwellung', 'Achselschwellung'],
    precautions: ['Nicht tief stechen']
  },
  {
    id: 'GB23',
    nameChinese: 'Zhejin',
    nameEnglish: 'Sinew Seat',
    nameGerman: 'Sehnensitz',
    meridian: 'GB',
    element: 'wood',
    location: '1 cun anterior zu GB22, auf Höhe der Brustwarze',
    depth: '0.3-0.5 cun schräg',
    frequency: 384.8,
    harmonicFrequencies: calculateHarmonics(384.8),
    pointTypes: ['regular'],
    functions: ['Reguliert Qi', 'Entspannt Sehnen'],
    indications: ['Rippenschmerzen', 'Asthma', 'Erbrechen'],
    precautions: ['Nicht tief stechen']
  },

  // ========== RUMPF-PUNKTE (GB24-GB30) ==========
  {
    id: 'GB24',
    nameChinese: 'Riyue',
    nameEnglish: 'Sun and Moon',
    nameGerman: 'Sonne und Mond',
    meridian: 'GB',
    element: 'wood',
    location: 'Im 7. ICR, auf der Mamillarlinie',
    depth: '0.5-0.8 cun schräg',
    frequency: 389.2,
    harmonicFrequencies: calculateHarmonics(389.2),
    pointTypes: ['mu_front'],
    functions: ['Reguliert Leber und Gallenblase', 'Harmonisiert Shaoyang'],
    indications: ['Gallenblasenentzündung', 'Rippenschmerzen', 'Erbrechen', 'bitterer Mundgeschmack'],
    precautions: ['Nicht tief stechen']
  },
  {
    id: 'GB25',
    nameChinese: 'Jingmen',
    nameEnglish: 'Capital Gate',
    nameGerman: 'Hauptstadttor',
    meridian: 'GB',
    element: 'wood',
    location: 'An der Spitze der 12. Rippe',
    depth: '0.5-1 cun',
    frequency: 393.6,
    harmonicFrequencies: calculateHarmonics(393.6),
    pointTypes: ['mu_front'],
    functions: ['Stärkt Nieren', 'Reguliert Wasserwege'],
    indications: ['Lendenschmerzen', 'Harnprobleme', 'Rippenschmerzen']
  },
  {
    id: 'GB26',
    nameChinese: 'Daimai',
    nameEnglish: 'Girdling Vessel',
    nameGerman: 'Gürtelgefäß',
    meridian: 'GB',
    element: 'wood',
    location: 'Auf der Höhe des Nabels, unter LR13',
    depth: '0.5-1 cun',
    frequency: 398,
    harmonicFrequencies: calculateHarmonics(398),
    pointTypes: ['regular'],
    functions: ['Reguliert Dai Mai', 'Reguliert Menstruation'],
    indications: ['Menstruationsstörungen', 'Leukorr', 'Lendenschmerzen', 'Hernie']
  },
  {
    id: 'GB27',
    nameChinese: 'Wushu',
    nameEnglish: 'Five Pivots',
    nameGerman: 'Fünf Drehpunkte',
    meridian: 'GB',
    element: 'wood',
    location: '3 cun unter dem Nabel, auf Höhe von REN4, lateral der Spina iliaca',
    depth: '0.5-1 cun',
    frequency: 402.4,
    harmonicFrequencies: calculateHarmonics(402.4),
    pointTypes: ['regular'],
    functions: ['Reguliert Dai Mai', 'Stärkt Lendenbereich'],
    indications: ['Leistenschmerzen', 'Hernie', 'Leukorr', 'Verstopfung']
  },
  {
    id: 'GB28',
    nameChinese: 'Weidao',
    nameEnglish: 'Linking Path',
    nameGerman: 'Verbindungspfad',
    meridian: 'GB',
    element: 'wood',
    location: '0.5 cun anterior und inferior zu GB27',
    depth: '0.5-1 cun',
    frequency: 406.8,
    harmonicFrequencies: calculateHarmonics(406.8),
    pointTypes: ['regular'],
    functions: ['Reguliert Dai Mai', 'Lindert Schmerzen'],
    indications: ['Leistenschmerzen', 'Leukorr', 'Prolaps']
  },
  {
    id: 'GB29',
    nameChinese: 'Juliao',
    nameEnglish: 'Stationary Crevice',
    nameGerman: 'Stationäre Spalte',
    meridian: 'GB',
    element: 'wood',
    location: 'Auf der Mitte zwischen Spina iliaca anterior superior und Trochanter major',
    depth: '1-1.5 cun',
    frequency: 411.2,
    harmonicFrequencies: calculateHarmonics(411.2),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind-Feuchtigkeit', 'Aktiviert Kanal'],
    indications: ['Hüftschmerzen', 'Beinlähmung', 'Lendenschmerzen']
  },
  {
    id: 'GB30',
    nameChinese: 'Huantiao',
    nameEnglish: 'Jumping Circle',
    nameGerman: 'Springender Kreis',
    meridian: 'GB',
    element: 'wood',
    location: 'Am Gesäß, am Schnittpunkt des lateralen und mittleren Drittels zwischen Trochanter major und Hiatus sacralis',
    depth: '2-3 cun',
    frequency: 415.6,
    harmonicFrequencies: calculateHarmonics(415.6),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind-Feuchtigkeit', 'Stärkt Lendenbereich und Beine'],
    indications: ['Ischias', 'Hüftschmerzen', 'Beinlähmung', 'Hauterkrankungen'],
    chakraCorrespondence: 'muladhara'
  },

  // ========== OBERSCHENKEL-PUNKTE (GB31-GB34) ==========
  {
    id: 'GB31',
    nameChinese: 'Fengshi',
    nameEnglish: 'Wind Market',
    nameGerman: 'Windmarkt',
    meridian: 'GB',
    element: 'wood',
    location: 'Lateral am Oberschenkel, wo die Mittelfingerspitze bei herabhängendem Arm endet',
    depth: '1-2 cun',
    frequency: 420,
    harmonicFrequencies: calculateHarmonics(420),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Juckreiz'],
    indications: ['Beinschmerzen', 'Lähmung', 'Urtikaria', 'Pruritus']
  },
  {
    id: 'GB32',
    nameChinese: 'Zhongdu',
    nameEnglish: 'Central River',
    nameGerman: 'Zentraler Fluss',
    meridian: 'GB',
    element: 'wood',
    location: '5 cun über dem lateralen Kniegelenk, zwischen Vastus lateralis und Bizeps femoris',
    depth: '1-2 cun',
    frequency: 424.4,
    harmonicFrequencies: calculateHarmonics(424.4),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Aktiviert Kanal'],
    indications: ['Oberschenkelschmerzen', 'Beinlähmung', 'Knieschmerzen']
  },
  {
    id: 'GB33',
    nameChinese: 'Xiyangguan',
    nameEnglish: 'Knee Yang Joint',
    nameGerman: 'Knie-Yang-Gelenk',
    meridian: 'GB',
    element: 'wood',
    location: '3 cun über GB34, in der Vertiefung zwischen Femur und Bizepssehne',
    depth: '0.5-1 cun',
    frequency: 428.8,
    harmonicFrequencies: calculateHarmonics(428.8),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind-Feuchtigkeit', 'Lindert Knieschmerzen'],
    indications: ['Knieschmerzen', 'Kniesteifigkeit', 'Unterschenkelschmerzen']
  },
  {
    id: 'GB34',
    nameChinese: 'Yanglingquan',
    nameEnglish: 'Yang Mound Spring',
    nameGerman: 'Yang-Hügel-Quelle',
    meridian: 'GB',
    element: 'wood',
    location: 'In der Vertiefung vor und unter dem Fibulaköpfchen',
    depth: '1-1.5 cun',
    frequency: 433.2,
    harmonicFrequencies: calculateHarmonics(433.2),
    pointTypes: ['he_sea', 'hui_meeting'],
    functions: ['Entspannt Sehnen', 'Reguliert Leber und Gallenblase', 'Zerstreut Feuchtigkeit'],
    indications: ['Knieschmerzen', 'Rippenschmerzen', 'Beinlähmung', 'Gallenblasenerkrankungen'],
    chakraCorrespondence: 'manipura'
  },

  // ========== UNTERSCHENKEL-PUNKTE (GB35-GB44) ==========
  {
    id: 'GB35',
    nameChinese: 'Yangjiao',
    nameEnglish: 'Yang Intersection',
    nameGerman: 'Yang-Kreuzung',
    meridian: 'GB',
    element: 'wood',
    location: '7 cun über dem Außenknöchel, am Hinterrand der Fibula',
    depth: '0.5-1 cun',
    frequency: 437.6,
    harmonicFrequencies: calculateHarmonics(437.6),
    pointTypes: ['xi_cleft'],
    functions: ['Beruhigt Geist', 'Aktiviert Kanal'],
    indications: ['Knieschmerzen', 'Brustschmerzen', 'Angst', 'Manie']
  },
  {
    id: 'GB36',
    nameChinese: 'Waiqiu',
    nameEnglish: 'Outer Hill',
    nameGerman: 'Äußerer Hügel',
    meridian: 'GB',
    element: 'wood',
    location: '7 cun über dem Außenknöchel, am Vorderrand der Fibula',
    depth: '0.5-1 cun',
    frequency: 442,
    harmonicFrequencies: calculateHarmonics(442),
    pointTypes: ['xi_cleft'],
    functions: ['Aktiviert Kanal', 'Lindert Schmerzen'],
    indications: ['Nackensteifigkeit', 'Brustschmerzen', 'Unterschenkelschmerzen']
  },
  {
    id: 'GB37',
    nameChinese: 'Guangming',
    nameEnglish: 'Bright Light',
    nameGerman: 'Helles Licht',
    meridian: 'GB',
    element: 'wood',
    location: '5 cun über dem Außenknöchel, am Vorderrand der Fibula',
    depth: '0.5-1 cun',
    frequency: 446.4,
    harmonicFrequencies: calculateHarmonics(446.4),
    pointTypes: ['luo_connecting'],
    functions: ['Erhellt Augen', 'Zerstreut Wind-Hitze'],
    indications: ['Augenerkrankungen', 'Nachtblindheit', 'Brustschmerzen', 'Unterschenkelschmerzen'],
    chakraCorrespondence: 'ajna'
  },
  {
    id: 'GB38',
    nameChinese: 'Yangfu',
    nameEnglish: 'Yang Assistance',
    nameGerman: 'Yang-Hilfe',
    meridian: 'GB',
    element: 'wood',
    location: '4 cun über dem Außenknöchel, am Vorderrand der Fibula',
    depth: '0.5-1 cun',
    frequency: 450.8,
    harmonicFrequencies: calculateHarmonics(450.8),
    pointTypes: ['jing_river'],
    functions: ['Zerstreut Wind-Hitze', 'Aktiviert Kanal'],
    indications: ['Migräne', 'Augenaußenwinkelschmerzen', 'Knöchelschmerzen']
  },
  {
    id: 'GB39',
    nameChinese: 'Xuanzhong',
    nameEnglish: 'Suspended Bell',
    nameGerman: 'Aufgehängte Glocke',
    meridian: 'GB',
    element: 'wood',
    location: '3 cun über dem Außenknöchel, am Hinterrand der Fibula',
    depth: '0.5-1 cun',
    frequency: 455.2,
    harmonicFrequencies: calculateHarmonics(455.2),
    pointTypes: ['hui_meeting'],
    functions: ['Nährt Mark', 'Stärkt Knochen', 'Aktiviert Kanal'],
    indications: ['Nackenschmerzen', 'Knöchelschmerzen', 'Knochenerkrankungen', 'Hemiplegie']
  },
  {
    id: 'GB40',
    nameChinese: 'Qiuxu',
    nameEnglish: 'Hill Ruins',
    nameGerman: 'Hügelruinen',
    meridian: 'GB',
    element: 'wood',
    location: 'Vor und unter dem Außenknöchel, in der Vertiefung lateral der Sehne',
    depth: '0.5-1 cun',
    frequency: 459.6,
    harmonicFrequencies: calculateHarmonics(459.6),
    pointTypes: ['yuan_source'],
    functions: ['Reguliert Leber und Gallenblase', 'Aktiviert Kanal'],
    indications: ['Knöchelschmerzen', 'Rippenschmerzen', 'bitterer Mundgeschmack', 'Gallenblasenerkrankungen']
  },
  {
    id: 'GB41',
    nameChinese: 'Foot Linqi',
    nameEnglish: 'Foot Overlooking Tears',
    nameGerman: 'Fußtränenübersicht',
    meridian: 'GB',
    element: 'wood',
    location: 'Auf dem Fußrücken, proximal des 4. und 5. Metatarsale',
    depth: '0.3-0.5 cun',
    frequency: 464,
    harmonicFrequencies: calculateHarmonics(464),
    pointTypes: ['shu_stream', 'confluent'],
    functions: ['Öffnet Dai Mai', 'Reguliert Leber-Qi', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Augenrötung', 'Brustschmerzen', 'Menstruationsstörungen'],
    chakraCorrespondence: 'svadhisthana'
  },
  {
    id: 'GB42',
    nameChinese: 'Diwuhui',
    nameEnglish: 'Earth Fivefold Convergence',
    nameGerman: 'Fünffache Erdenvereinigung',
    meridian: 'GB',
    element: 'wood',
    location: 'Zwischen 4. und 5. Metatarsale, distal von GB41',
    depth: '0.3-0.5 cun',
    frequency: 468.4,
    harmonicFrequencies: calculateHarmonics(468.4),
    pointTypes: ['regular'],
    functions: ['Reguliert Qi', 'Lindert Schwellung'],
    indications: ['Mastitis', 'Augenrötung', 'Fußrückenschmerzen']
  },
  {
    id: 'GB43',
    nameChinese: 'Xiaxi',
    nameEnglish: 'Pinched Ravine',
    nameGerman: 'Eingeklemmte Schlucht',
    meridian: 'GB',
    element: 'wood',
    location: 'Zwischen 4. und 5. Zehe, proximal des Schwimmhautrandes',
    depth: '0.3-0.5 cun',
    frequency: 472.8,
    harmonicFrequencies: calculateHarmonics(472.8),
    pointTypes: ['ying_spring'],
    functions: ['Klärt Hitze', 'Zerstreut Wind'],
    indications: ['Kopfschmerzen', 'Schwindel', 'Tinnitus', 'Brustschmerzen']
  },
  {
    id: 'GB44',
    nameChinese: 'Foot Qiaoyin',
    nameEnglish: 'Foot Yin Portals',
    nameGerman: 'Fußyinportale',
    meridian: 'GB',
    element: 'wood',
    location: 'Am 4. Zeh, 0.1 cun lateral des Nagelwinkels',
    depth: '0.1 cun oder Blutenlassen',
    frequency: 477.2,
    harmonicFrequencies: calculateHarmonics(477.2),
    pointTypes: ['jing_well'],
    functions: ['Klärt Hitze', 'Unterdrückt Yang', 'Beruhigt Geist'],
    indications: ['Kopfschmerzen', 'Tinnitus', 'Schlaflosigkeit', 'Rippenschmerzen']
  }
];
