/**
 * NIERENMERIDIAN (KI) - 27 Punkte
 * Element: Wasser (Yin), Maximalzeit: 17-19 Uhr
 * WHO Standard Acupuncture Point Locations (2008)
 */

import { AcupuncturePoint, calculateHarmonics } from '../meridianPointsDatabase';

export const KIDNEY_MERIDIAN: AcupuncturePoint[] = [
  {
    id: 'KI1',
    nameChinese: 'Yongquan',
    nameEnglish: 'Gushing Spring',
    nameGerman: 'Sprudelnde Quelle',
    meridian: 'KI',
    element: 'water',
    location: 'Auf der Fußsohle, zwischen 2. und 3. Metatarsale, im vorderen Drittel',
    depth: '0.5-1 cun',
    frequency: 192,
    harmonicFrequencies: calculateHarmonics(192),
    pointTypes: ['jing_well'],
    functions: ['Senkt Hitze', 'Beruhigt Geist', 'Belebt Bewusstsein', 'Tonisiert Yin'],
    indications: ['Bewusstlosigkeit', 'Schock', 'Kopfschmerzen', 'Schlaflosigkeit', 'Fußsohlenschmerzen'],
    chakraCorrespondence: 'muladhara'
  },
  {
    id: 'KI2',
    nameChinese: 'Rangu',
    nameEnglish: 'Blazing Valley',
    nameGerman: 'Brennendes Tal',
    meridian: 'KI',
    element: 'water',
    location: 'Medial am Fuß, unterhalb der Tuberositas ossis navicularis',
    depth: '0.5-1 cun',
    frequency: 197.3,
    harmonicFrequencies: calculateHarmonics(197.3),
    pointTypes: ['ying_spring'],
    functions: ['Klärt Nieren-Leere-Hitze', 'Kühlt Blut'],
    indications: ['Nachtschweiß', 'Halsschmerzen', 'Menstruationsstörungen', 'Fußschmerzen']
  },
  {
    id: 'KI3',
    nameChinese: 'Taixi',
    nameEnglish: 'Supreme Stream',
    nameGerman: 'Höchster Bach',
    meridian: 'KI',
    element: 'water',
    location: 'Zwischen medialem Malleolus und Achillessehne',
    depth: '0.5-1 cun',
    frequency: 202.6,
    harmonicFrequencies: calculateHarmonics(202.6),
    pointTypes: ['shu_stream', 'yuan_source'],
    functions: ['Tonisiert Nieren', 'Stärkt Lendenbereich', 'Reguliert Uterus'],
    indications: ['Lendenschmerzen', 'Tinnitus', 'Impotenz', 'Menstruationsstörungen', 'Schlaflosigkeit'],
    chakraCorrespondence: 'svadhisthana'
  },
  {
    id: 'KI4',
    nameChinese: 'Dazhong',
    nameEnglish: 'Large Goblet',
    nameGerman: 'Großer Kelch',
    meridian: 'KI',
    element: 'water',
    location: '0.5 cun unter KI3, am Ansatz der Achillessehne',
    depth: '0.3-0.5 cun',
    frequency: 207.9,
    harmonicFrequencies: calculateHarmonics(207.9),
    pointTypes: ['luo_connecting'],
    functions: ['Stärkt Willenskraft', 'Hebt Geist'],
    indications: ['Fersenschmerzen', 'Asthma', 'Blut im Urin', 'Willenslosigkeit']
  },
  {
    id: 'KI5',
    nameChinese: 'Shuiquan',
    nameEnglish: 'Water Spring',
    nameGerman: 'Wasserquelle',
    meridian: 'KI',
    element: 'water',
    location: '1 cun unter KI3, in der Vertiefung vor der Achillessehne',
    depth: '0.3-0.5 cun',
    frequency: 213.2,
    harmonicFrequencies: calculateHarmonics(213.2),
    pointTypes: ['xi_cleft'],
    functions: ['Reguliert Uterus', 'Belebt Blut'],
    indications: ['Dysmenorrhoe', 'Amenorrhoe', 'Prolaps', 'Sehstörungen']
  },
  {
    id: 'KI6',
    nameChinese: 'Zhaohai',
    nameEnglish: 'Shining Sea',
    nameGerman: 'Strahlendes Meer',
    meridian: 'KI',
    element: 'water',
    location: '1 cun unter dem medialen Malleolus',
    depth: '0.3-0.5 cun',
    frequency: 218.5,
    harmonicFrequencies: calculateHarmonics(218.5),
    pointTypes: ['confluent'],
    functions: ['Öffnet Yin Qiao Mai', 'Nährt Nieren-Yin', 'Befeuchtet Kehle'],
    indications: ['Schlaflosigkeit', 'Halsschmerzen', 'Menstruationsstörungen', 'Epilepsie'],
    chakraCorrespondence: 'vishuddha'
  },
  {
    id: 'KI7',
    nameChinese: 'Fuliu',
    nameEnglish: 'Recover Flow',
    nameGerman: 'Wiederhergestellter Fluss',
    meridian: 'KI',
    element: 'water',
    location: '2 cun über KI3, am Vorderrand der Achillessehne',
    depth: '0.5-1 cun',
    frequency: 223.8,
    harmonicFrequencies: calculateHarmonics(223.8),
    pointTypes: ['jing_river'],
    functions: ['Tonisiert Nieren-Yang', 'Reguliert Schwitzen'],
    indications: ['Ödeme', 'Spontanschweiß', 'Durchfall', 'Lendenschmerzen']
  },
  {
    id: 'KI8',
    nameChinese: 'Jiaoxin',
    nameEnglish: 'Intersection Reach',
    nameGerman: 'Kreuzungsreichweite',
    meridian: 'KI',
    element: 'water',
    location: '2 cun über KI3, 0.5 cun anterior von KI7',
    depth: '0.5-1 cun',
    frequency: 229.1,
    harmonicFrequencies: calculateHarmonics(229.1),
    pointTypes: ['xi_cleft'],
    functions: ['Reguliert Yin Qiao Mai', 'Reguliert Menstruation'],
    indications: ['Menstruationsstörungen', 'Uterusblutung', 'Prolaps']
  },
  {
    id: 'KI9',
    nameChinese: 'Zhubin',
    nameEnglish: 'Guest House',
    nameGerman: 'Gasthaus',
    meridian: 'KI',
    element: 'water',
    location: '5 cun über KI3, am medialen Rand des Gastrocnemius',
    depth: '1-1.5 cun',
    frequency: 234.4,
    harmonicFrequencies: calculateHarmonics(234.4),
    pointTypes: ['xi_cleft'],
    functions: ['Reguliert Yin Wei Mai', 'Beruhigt Geist'],
    indications: ['Manie', 'Wadenkrämpfe', 'Erbrechen', 'Hernie']
  },
  {
    id: 'KI10',
    nameChinese: 'Yingu',
    nameEnglish: 'Yin Valley',
    nameGerman: 'Yin-Tal',
    meridian: 'KI',
    element: 'water',
    location: 'Medial in der Kniekehle, zwischen den Sehnen',
    depth: '1-1.5 cun',
    frequency: 239.7,
    harmonicFrequencies: calculateHarmonics(239.7),
    pointTypes: ['he_sea'],
    functions: ['Tonisiert Nieren-Yin', 'Klärt Feuchtigkeit-Hitze'],
    indications: ['Impotenz', 'Hernie', 'Uterusblutung', 'Knieschmerzen'],
    chakraCorrespondence: 'svadhisthana'
  },
  {
    id: 'KI11',
    nameChinese: 'Henggu',
    nameEnglish: 'Pubic Bone',
    nameGerman: 'Schambein',
    meridian: 'KI',
    element: 'water',
    location: '0.5 cun lateral der Mittellinie, am oberen Rand des Schambeins',
    depth: '0.5-1 cun',
    frequency: 245,
    harmonicFrequencies: calculateHarmonics(245),
    pointTypes: ['regular'],
    functions: ['Tonisiert Nieren', 'Reguliert Urogenitalsystem'],
    indications: ['Impotenz', 'Hernie', 'Harnprobleme']
  },
  {
    id: 'KI12',
    nameChinese: 'Dahe',
    nameEnglish: 'Great Manifestation',
    nameGerman: 'Große Manifestation',
    meridian: 'KI',
    element: 'water',
    location: '0.5 cun lateral der Mittellinie, 1 cun über KI11',
    depth: '0.5-1 cun',
    frequency: 250.3,
    harmonicFrequencies: calculateHarmonics(250.3),
    pointTypes: ['regular'],
    functions: ['Tonisiert Nieren', 'Reguliert Chong Mai'],
    indications: ['Impotenz', 'Leukorr', 'Prolaps']
  },
  {
    id: 'KI13',
    nameChinese: 'Qixue',
    nameEnglish: 'Qi Hole',
    nameGerman: 'Qi-Loch',
    meridian: 'KI',
    element: 'water',
    location: '0.5 cun lateral der Mittellinie, 3 cun unter dem Nabel',
    depth: '0.5-1 cun',
    frequency: 255.6,
    harmonicFrequencies: calculateHarmonics(255.6),
    pointTypes: ['regular'],
    functions: ['Reguliert Chong Mai', 'Tonisiert Nieren'],
    indications: ['Menstruationsstörungen', 'Durchfall', 'Lendenschmerzen']
  },
  {
    id: 'KI14',
    nameChinese: 'Siman',
    nameEnglish: 'Fourfold Fullness',
    nameGerman: 'Vierfache Fülle',
    meridian: 'KI',
    element: 'water',
    location: '0.5 cun lateral der Mittellinie, 2 cun unter dem Nabel',
    depth: '0.5-1 cun',
    frequency: 260.9,
    harmonicFrequencies: calculateHarmonics(260.9),
    pointTypes: ['regular'],
    functions: ['Reguliert Menstruation', 'Fördert Wasserlassen'],
    indications: ['Menstruationsstörungen', 'Postpartale Schmerzen', 'Ödeme']
  },
  {
    id: 'KI16',
    nameChinese: 'Huangshu',
    nameEnglish: 'Vitals Shu',
    nameGerman: 'Vitaler Transportpunkt',
    meridian: 'KI',
    element: 'water',
    location: '0.5 cun lateral des Nabels',
    depth: '0.5-1 cun',
    frequency: 271.5,
    harmonicFrequencies: calculateHarmonics(271.5),
    pointTypes: ['regular'],
    functions: ['Reguliert Darm-Qi', 'Lindert Schmerzen'],
    indications: ['Bauchschmerzen', 'Verstopfung', 'Durchfall']
  },
  {
    id: 'KI21',
    nameChinese: 'Youmen',
    nameEnglish: 'Dark Gate',
    nameGerman: 'Dunkles Tor',
    meridian: 'KI',
    element: 'water',
    location: '0.5 cun lateral der Mittellinie, 6 cun über dem Nabel',
    depth: '0.5-1 cun',
    frequency: 298,
    harmonicFrequencies: calculateHarmonics(298),
    pointTypes: ['regular'],
    functions: ['Harmonisiert Magen', 'Senkt rebellierendes Qi'],
    indications: ['Übelkeit', 'Erbrechen', 'Bauchschmerzen']
  },
  {
    id: 'KI22',
    nameChinese: 'Bulang',
    nameEnglish: 'Walking Corridor',
    nameGerman: 'Wandelnder Korridor',
    meridian: 'KI',
    element: 'water',
    location: '2 cun lateral der Mittellinie, im 5. ICR',
    depth: '0.5-0.8 cun schräg',
    frequency: 303.3,
    harmonicFrequencies: calculateHarmonics(303.3),
    pointTypes: ['regular'],
    functions: ['Senkt rebellierendes Qi', 'Lindert Husten'],
    indications: ['Husten', 'Asthma', 'Brustschmerzen'],
    precautions: ['Nicht tief stechen']
  },
  {
    id: 'KI23',
    nameChinese: 'Shenfeng',
    nameEnglish: 'Spirit Seal',
    nameGerman: 'Geistsiegel',
    meridian: 'KI',
    element: 'water',
    location: '2 cun lateral der Mittellinie, im 4. ICR',
    depth: '0.5-0.8 cun schräg',
    frequency: 308.6,
    harmonicFrequencies: calculateHarmonics(308.6),
    pointTypes: ['regular'],
    functions: ['Reguliert Qi im Brustkorb', 'Beruhigt Geist'],
    indications: ['Husten', 'Asthma', 'Brustschmerzen', 'Mastitis'],
    precautions: ['Nicht tief stechen']
  },
  {
    id: 'KI24',
    nameChinese: 'Lingxu',
    nameEnglish: 'Spirit Ruins',
    nameGerman: 'Geistesruinen',
    meridian: 'KI',
    element: 'water',
    location: '2 cun lateral der Mittellinie, im 3. ICR',
    depth: '0.5-0.8 cun schräg',
    frequency: 313.9,
    harmonicFrequencies: calculateHarmonics(313.9),
    pointTypes: ['regular'],
    functions: ['Reguliert Qi', 'Lindert Husten'],
    indications: ['Husten', 'Asthma', 'Brustschmerzen'],
    precautions: ['Nicht tief stechen']
  },
  {
    id: 'KI25',
    nameChinese: 'Shencang',
    nameEnglish: 'Spirit Storehouse',
    nameGerman: 'Geistesspeicher',
    meridian: 'KI',
    element: 'water',
    location: '2 cun lateral der Mittellinie, im 2. ICR',
    depth: '0.5-0.8 cun schräg',
    frequency: 319.2,
    harmonicFrequencies: calculateHarmonics(319.2),
    pointTypes: ['regular'],
    functions: ['Reguliert Qi', 'Lindert Husten'],
    indications: ['Husten', 'Asthma', 'Brustschmerzen'],
    precautions: ['Nicht tief stechen']
  },
  {
    id: 'KI26',
    nameChinese: 'Yuzhong',
    nameEnglish: 'Lively Center',
    nameGerman: 'Lebendige Mitte',
    meridian: 'KI',
    element: 'water',
    location: '2 cun lateral der Mittellinie, im 1. ICR',
    depth: '0.5-0.8 cun schräg',
    frequency: 324.5,
    harmonicFrequencies: calculateHarmonics(324.5),
    pointTypes: ['regular'],
    functions: ['Reguliert Qi', 'Lindert Husten'],
    indications: ['Husten', 'Asthma', 'Brustschmerzen'],
    precautions: ['Nicht tief stechen']
  },
  {
    id: 'KI27',
    nameChinese: 'Shufu',
    nameEnglish: 'Shu Mansion',
    nameGerman: 'Transportpunkt-Palast',
    meridian: 'KI',
    element: 'water',
    location: '2 cun lateral der Mittellinie, in der Vertiefung unter der Clavicula',
    depth: '0.5-0.8 cun schräg',
    frequency: 329.8,
    harmonicFrequencies: calculateHarmonics(329.8),
    pointTypes: ['regular'],
    functions: ['Tonisiert Nieren', 'Senkt rebellierendes Qi', 'Lindert Husten'],
    indications: ['Husten', 'Asthma', 'Brustschmerzen', 'Erbrechen'],
    precautions: ['Nicht tief stechen'],
    chakraCorrespondence: 'vishuddha'
  }
];
