/**
 * LEBERMERIDIAN (LR) - 14 Punkte
 * Element: Holz (Yin), Maximalzeit: 1-3 Uhr
 * WHO Standard Acupuncture Point Locations (2008)
 */

import { AcupuncturePoint, calculateHarmonics } from '../meridianPointsDatabase';

export const LIVER_MERIDIAN: AcupuncturePoint[] = [
  {
    id: 'LR1',
    nameChinese: 'Dadun',
    nameEnglish: 'Large Pile',
    nameGerman: 'Großer Haufen',
    meridian: 'LR',
    element: 'wood',
    location: 'Am großen Zeh, 0.1 cun proximal des lateralen Nagelwinkels',
    depth: '0.1-0.2 cun oder Blutenlassen',
    frequency: 288,
    harmonicFrequencies: calculateHarmonics(288),
    pointTypes: ['jing_well'],
    functions: ['Reguliert Leber-Qi', 'Reguliert untere Körperöffnungen'],
    indications: ['Hernie', 'Uterusblutung', 'Enuresis', 'Epilepsie'],
    chakraCorrespondence: 'muladhara'
  },
  {
    id: 'LR2',
    nameChinese: 'Xingjian',
    nameEnglish: 'Moving Between',
    nameGerman: 'Dazwischen Bewegen',
    meridian: 'LR',
    element: 'wood',
    location: 'Zwischen 1. und 2. Zehe, proximal des Schwimmhautrandes',
    depth: '0.5-1 cun',
    frequency: 295.4,
    harmonicFrequencies: calculateHarmonics(295.4),
    pointTypes: ['ying_spring'],
    functions: ['Klärt Leber-Feuer', 'Kühlt Blut', 'Beruhigt Leber-Yang'],
    indications: ['Kopfschmerzen', 'Augenrötung', 'Schlaflosigkeit', 'Menstruationsstörungen']
  },
  {
    id: 'LR3',
    nameChinese: 'Taichong',
    nameEnglish: 'Supreme Rushing',
    nameGerman: 'Höchstes Drängen',
    meridian: 'LR',
    element: 'wood',
    location: 'Auf dem Fußrücken, zwischen 1. und 2. Metatarsale, in der Vertiefung distal ihrer Verbindung',
    depth: '0.5-1 cun',
    frequency: 302.8,
    harmonicFrequencies: calculateHarmonics(302.8),
    pointTypes: ['shu_stream', 'yuan_source'],
    functions: ['Reguliert Leber-Qi', 'Unterdrückt Leber-Yang', 'Nährt Leber-Blut'],
    indications: ['Kopfschmerzen', 'Schwindel', 'Augenkrankheiten', 'Menstruationsstörungen', 'Reizbarkeit'],
    chakraCorrespondence: 'manipura'
  },
  {
    id: 'LR4',
    nameChinese: 'Zhongfeng',
    nameEnglish: 'Mound Center',
    nameGerman: 'Hügelmitte',
    meridian: 'LR',
    element: 'wood',
    location: 'Vor dem medialen Malleolus, medial der Sehne des M. tibialis anterior',
    depth: '0.5-1 cun',
    frequency: 310.2,
    harmonicFrequencies: calculateHarmonics(310.2),
    pointTypes: ['jing_river'],
    functions: ['Reguliert Leber-Qi', 'Zerstreut Stagnation'],
    indications: ['Hernie', 'Lendenschmerzen', 'Harnverhalt', 'Knöchelschmerzen']
  },
  {
    id: 'LR5',
    nameChinese: 'Ligou',
    nameEnglish: 'Woodworm Canal',
    nameGerman: 'Holzwurmkanal',
    meridian: 'LR',
    element: 'wood',
    location: '5 cun über dem medialen Malleolus, am Hinterrand der Tibia',
    depth: '0.5-1 cun',
    frequency: 317.6,
    harmonicFrequencies: calculateHarmonics(317.6),
    pointTypes: ['luo_connecting'],
    functions: ['Reguliert Leber-Qi', 'Reguliert Menstruation'],
    indications: ['Menstruationsstörungen', 'Leukorr', 'Hernie', 'Harnprobleme']
  },
  {
    id: 'LR6',
    nameChinese: 'Zhongdu',
    nameEnglish: 'Central Metropolis',
    nameGerman: 'Zentrale Metropole',
    meridian: 'LR',
    element: 'wood',
    location: '7 cun über dem medialen Malleolus, am Hinterrand der Tibia',
    depth: '0.5-1 cun',
    frequency: 325,
    harmonicFrequencies: calculateHarmonics(325),
    pointTypes: ['xi_cleft'],
    functions: ['Reguliert Leber-Qi', 'Stoppt Blutungen'],
    indications: ['Menorrhagie', 'Hernie', 'Bauchschmerzen']
  },
  {
    id: 'LR7',
    nameChinese: 'Xiguan',
    nameEnglish: 'Knee Joint',
    nameGerman: 'Kniegelenk',
    meridian: 'LR',
    element: 'wood',
    location: '1 cun posterior und inferior des medialen Tibiakondylus',
    depth: '0.5-1 cun',
    frequency: 332.4,
    harmonicFrequencies: calculateHarmonics(332.4),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind-Feuchtigkeit', 'Lindert Schmerzen'],
    indications: ['Knieschmerzen', 'Unterschenkelschmerzen']
  },
  {
    id: 'LR8',
    nameChinese: 'Ququan',
    nameEnglish: 'Spring at the Bend',
    nameGerman: 'Quelle an der Beuge',
    meridian: 'LR',
    element: 'wood',
    location: 'Am medialen Ende der Kniekehle, bei gebeugtem Knie, am Hinterrand des medialen Tibiakondylus',
    depth: '1-1.5 cun',
    frequency: 339.8,
    harmonicFrequencies: calculateHarmonics(339.8),
    pointTypes: ['he_sea'],
    functions: ['Nährt Leber-Blut', 'Reguliert Menstruation', 'Löst Feuchtigkeit'],
    indications: ['Menstruationsstörungen', 'Leukorr', 'Knieschmerzen', 'Impotenz'],
    chakraCorrespondence: 'svadhisthana'
  },
  {
    id: 'LR9',
    nameChinese: 'Yinbao',
    nameEnglish: 'Yin Wrapping',
    nameGerman: 'Yin-Umhüllung',
    meridian: 'LR',
    element: 'wood',
    location: '4 cun über dem medialen Knie, zwischen M. sartorius und M. gracilis',
    depth: '0.5-1 cun',
    frequency: 347.2,
    harmonicFrequencies: calculateHarmonics(347.2),
    pointTypes: ['regular'],
    functions: ['Reguliert untere Körperöffnungen'],
    indications: ['Lendenschmerzen', 'Hernie', 'Menstruationsstörungen']
  },
  {
    id: 'LR10',
    nameChinese: 'Foot Wuli',
    nameEnglish: 'Foot Five Miles',
    nameGerman: 'Fünf Meilen des Fußes',
    meridian: 'LR',
    element: 'wood',
    location: '3 cun unter ST30, am medialen Rand des M. adductor longus',
    depth: '0.5-1 cun',
    frequency: 354.6,
    harmonicFrequencies: calculateHarmonics(354.6),
    pointTypes: ['regular'],
    functions: ['Reguliert Leber-Qi'],
    indications: ['Hernie', 'Lendenschmerzen', 'Harnverhalt']
  },
  {
    id: 'LR11',
    nameChinese: 'Yinlian',
    nameEnglish: 'Yin Corner',
    nameGerman: 'Yin-Ecke',
    meridian: 'LR',
    element: 'wood',
    location: '2 cun unter ST30, am medialen Rand des M. adductor longus',
    depth: '0.5-1 cun',
    frequency: 362,
    harmonicFrequencies: calculateHarmonics(362),
    pointTypes: ['regular'],
    functions: ['Reguliert Menstruation'],
    indications: ['Menstruationsstörungen', 'Leistenschmerzen']
  },
  {
    id: 'LR12',
    nameChinese: 'Jimai',
    nameEnglish: 'Urgent Pulse',
    nameGerman: 'Dringender Puls',
    meridian: 'LR',
    element: 'wood',
    location: '2.5 cun lateral der Mittellinie, lateral der A. femoralis',
    depth: '0.5-1 cun',
    frequency: 369.4,
    harmonicFrequencies: calculateHarmonics(369.4),
    pointTypes: ['regular'],
    functions: ['Reguliert Leber-Qi', 'Lindert Schmerzen'],
    indications: ['Hernie', 'Leistenschmerzen', 'Genitalbeschwerden'],
    precautions: ['Vorsicht - A. femoralis']
  },
  {
    id: 'LR13',
    nameChinese: 'Zhangmen',
    nameEnglish: 'Camphorwood Gate',
    nameGerman: 'Kampferholztor',
    meridian: 'LR',
    element: 'wood',
    location: 'An der Spitze der 11. Rippe',
    depth: '0.5-1 cun',
    frequency: 376.8,
    harmonicFrequencies: calculateHarmonics(376.8),
    pointTypes: ['mu_front', 'hui_meeting'],
    functions: ['Harmonisiert Leber und Milz', 'Stärkt Milz', 'Reguliert Qi'],
    indications: ['Bauchschmerzen', 'Durchfall', 'Rippenschmerzen', 'Hepatosplenomegalie'],
    chakraCorrespondence: 'manipura'
  },
  {
    id: 'LR14',
    nameChinese: 'Qimen',
    nameEnglish: 'Cycle Gate',
    nameGerman: 'Zyklustor',
    meridian: 'LR',
    element: 'wood',
    location: 'Im 6. ICR, auf der Mamillarlinie',
    depth: '0.5-0.8 cun schräg',
    frequency: 384.2,
    harmonicFrequencies: calculateHarmonics(384.2),
    pointTypes: ['mu_front'],
    functions: ['Reguliert Leber-Qi', 'Belebt Blut', 'Harmonisiert Magen'],
    indications: ['Rippenschmerzen', 'Brustschmerzen', 'Mastitis', 'Depression'],
    precautions: ['Nicht tief stechen'],
    chakraCorrespondence: 'anahata'
  }
];
