/**
 * DÜNNDARMMERIDIAN (SI) - 19 Punkte
 * Element: Feuer (Yang), Maximalzeit: 13-15 Uhr
 * WHO Standard Acupuncture Point Locations (2008)
 */

import { AcupuncturePoint, calculateHarmonics } from '../meridianPointsDatabase';

export const SMALL_INTESTINE_MERIDIAN: AcupuncturePoint[] = [
  {
    id: 'SI1',
    nameChinese: 'Shaoze',
    nameEnglish: 'Lesser Marsh',
    nameGerman: 'Kleiner Sumpf',
    meridian: 'SI',
    element: 'fire',
    location: 'Am kleinen Finger, 0.1 cun proximal des ulnaren Nagelwinkels',
    depth: '0.1 cun oder Blutenlassen',
    frequency: 343.5,
    harmonicFrequencies: calculateHarmonics(343.5),
    pointTypes: ['jing_well'],
    functions: ['Klärt Hitze', 'Fördert Laktation', 'Belebt Bewusstsein'],
    indications: ['Kopfschmerzen', 'Fieber', 'Laktationsprobleme', 'Konjunktivitis']
  },
  {
    id: 'SI2',
    nameChinese: 'Qiangu',
    nameEnglish: 'Front Valley',
    nameGerman: 'Vorderes Tal',
    meridian: 'SI',
    element: 'fire',
    location: 'Ulnar am kleinen Finger, distal des 5. MCP-Gelenks',
    depth: '0.3-0.5 cun',
    frequency: 350.4,
    harmonicFrequencies: calculateHarmonics(350.4),
    pointTypes: ['ying_spring'],
    functions: ['Klärt Hitze', 'Fördert Laktation'],
    indications: ['Fieber', 'Tinnitus', 'Kopfschmerzen']
  },
  {
    id: 'SI3',
    nameChinese: 'Houxi',
    nameEnglish: 'Back Stream',
    nameGerman: 'Hinterer Bach',
    meridian: 'SI',
    element: 'fire',
    location: 'Ulnar an der Hand, proximal des 5. MCP-Gelenks, bei geballter Faust',
    depth: '0.5-1 cun',
    frequency: 357.3,
    harmonicFrequencies: calculateHarmonics(357.3),
    pointTypes: ['shu_stream', 'confluent'],
    functions: ['Öffnet Du Mai', 'Zerstreut Wind', 'Lindert Nacken und Rücken'],
    indications: ['Nackensteifigkeit', 'Kopfschmerzen', 'Rückenschmerzen', 'Epilepsie'],
    chakraCorrespondence: 'vishuddha'
  },
  {
    id: 'SI4',
    nameChinese: 'Wangu',
    nameEnglish: 'Wrist Bone',
    nameGerman: 'Handgelenkknochen',
    meridian: 'SI',
    element: 'fire',
    location: 'Ulnar am Handgelenk, in der Vertiefung zwischen Os triquetrum und Os pisiforme',
    depth: '0.3-0.5 cun',
    frequency: 364.2,
    harmonicFrequencies: calculateHarmonics(364.2),
    pointTypes: ['yuan_source'],
    functions: ['Klärt Hitze', 'Aktiviert Kanal'],
    indications: ['Handgelenkschmerzen', 'Fieber', 'Gelbsucht']
  },
  {
    id: 'SI5',
    nameChinese: 'Yanggu',
    nameEnglish: 'Yang Valley',
    nameGerman: 'Yang-Tal',
    meridian: 'SI',
    element: 'fire',
    location: 'Ulnar am Handgelenk, in der Vertiefung zwischen Ulna und Os triquetrum',
    depth: '0.3-0.5 cun',
    frequency: 371.1,
    harmonicFrequencies: calculateHarmonics(371.1),
    pointTypes: ['jing_river'],
    functions: ['Klärt Hitze', 'Lindert Schwellung'],
    indications: ['Handgelenkschmerzen', 'Tinnitus', 'Fieber']
  },
  {
    id: 'SI6',
    nameChinese: 'Yanglao',
    nameEnglish: 'Nursing the Aged',
    nameGerman: 'Pflege des Alten',
    meridian: 'SI',
    element: 'fire',
    location: '1 cun proximal von SI5, in der Vertiefung radial des Ulnaköpfchens',
    depth: '0.3-0.5 cun',
    frequency: 378,
    harmonicFrequencies: calculateHarmonics(378),
    pointTypes: ['xi_cleft'],
    functions: ['Erhellt Augen', 'Aktiviert Kanal'],
    indications: ['Sehstörungen', 'Schulter- und Armschmerzen', 'Steifer Nacken']
  },
  {
    id: 'SI7',
    nameChinese: 'Zhizheng',
    nameEnglish: 'Branch to the Correct',
    nameGerman: 'Zweig zum Richtigen',
    meridian: 'SI',
    element: 'fire',
    location: '5 cun proximal von SI5, auf der Verbindung SI5-SI8',
    depth: '0.5-1 cun',
    frequency: 384.9,
    harmonicFrequencies: calculateHarmonics(384.9),
    pointTypes: ['luo_connecting'],
    functions: ['Beruhigt Geist', 'Klärt Hitze'],
    indications: ['Kopfschmerzen', 'Nackensteifigkeit', 'Angst', 'Manie']
  },
  {
    id: 'SI8',
    nameChinese: 'Xiaohai',
    nameEnglish: 'Small Sea',
    nameGerman: 'Kleines Meer',
    meridian: 'SI',
    element: 'fire',
    location: 'Bei gebeugtem Ellenbogen, in der Vertiefung zwischen Olekranon und medialem Epikondylus',
    depth: '0.5-1 cun',
    frequency: 391.8,
    harmonicFrequencies: calculateHarmonics(391.8),
    pointTypes: ['he_sea'],
    functions: ['Klärt Hitze', 'Beruhigt Geist', 'Aktiviert Kanal'],
    indications: ['Ellenbogenschmerzen', 'Taubheit des Arms', 'Epilepsie']
  },
  {
    id: 'SI9',
    nameChinese: 'Jianzhen',
    nameEnglish: 'True Shoulder',
    nameGerman: 'Wahre Schulter',
    meridian: 'SI',
    element: 'fire',
    location: '1 cun über dem hinteren Achselfaltenende, bei adduziertem Arm',
    depth: '1-1.5 cun',
    frequency: 398.7,
    harmonicFrequencies: calculateHarmonics(398.7),
    pointTypes: ['regular'],
    functions: ['Aktiviert Kanal', 'Lindert Schmerzen'],
    indications: ['Schulterschmerzen', 'Armlähmung', 'Tinnitus']
  },
  {
    id: 'SI10',
    nameChinese: 'Naoshu',
    nameEnglish: 'Upper Arm Shu',
    nameGerman: 'Oberarm-Transportpunkt',
    meridian: 'SI',
    element: 'fire',
    location: 'Direkt über SI9, in der Vertiefung unter der Spina scapulae',
    depth: '0.5-1 cun',
    frequency: 405.6,
    harmonicFrequencies: calculateHarmonics(405.6),
    pointTypes: ['regular'],
    functions: ['Aktiviert Kanal', 'Lindert Schmerzen'],
    indications: ['Schulterschmerzen', 'Schultersteifigkeit']
  },
  {
    id: 'SI11',
    nameChinese: 'Tianzong',
    nameEnglish: 'Celestial Gathering',
    nameGerman: 'Himmlische Versammlung',
    meridian: 'SI',
    element: 'fire',
    location: 'In der Mitte der Fossa infraspinata, auf der Verbindung SI10-SI13',
    depth: '0.5-1 cun',
    frequency: 412.5,
    harmonicFrequencies: calculateHarmonics(412.5),
    pointTypes: ['regular'],
    functions: ['Aktiviert Kanal', 'Lindert Schmerzen', 'Fördert Laktation'],
    indications: ['Schulterschmerzen', 'Armschmerzen', 'Mastitis']
  },
  {
    id: 'SI12',
    nameChinese: 'Bingfeng',
    nameEnglish: 'Grasping the Wind',
    nameGerman: 'Wind Ergreifen',
    meridian: 'SI',
    element: 'fire',
    location: 'In der Mitte der Fossa supraspinata, über SI11',
    depth: '0.5-1 cun',
    frequency: 419.4,
    harmonicFrequencies: calculateHarmonics(419.4),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Aktiviert Kanal'],
    indications: ['Schulterschmerzen', 'Taubheit der Schulter']
  },
  {
    id: 'SI13',
    nameChinese: 'Quyuan',
    nameEnglish: 'Crooked Wall',
    nameGerman: 'Gekrümmte Mauer',
    meridian: 'SI',
    element: 'fire',
    location: 'Am medialen Ende der Fossa supraspinata',
    depth: '0.5-1 cun',
    frequency: 426.3,
    harmonicFrequencies: calculateHarmonics(426.3),
    pointTypes: ['regular'],
    functions: ['Aktiviert Kanal', 'Lindert Schmerzen'],
    indications: ['Schulterschmerzen', 'Schulterblattschmerzen']
  },
  {
    id: 'SI14',
    nameChinese: 'Jianwaishu',
    nameEnglish: 'Outer Shoulder Shu',
    nameGerman: 'Äußerer Schulter-Transportpunkt',
    meridian: 'SI',
    element: 'fire',
    location: '3 cun lateral des Dornfortsatzes T1',
    depth: '0.5-1 cun',
    frequency: 433.2,
    harmonicFrequencies: calculateHarmonics(433.2),
    pointTypes: ['regular'],
    functions: ['Aktiviert Kanal', 'Lindert Schmerzen'],
    indications: ['Schulter- und Rückenschmerzen', 'Nackensteifigkeit']
  },
  {
    id: 'SI15',
    nameChinese: 'Jianzhongshu',
    nameEnglish: 'Middle Shoulder Shu',
    nameGerman: 'Mittlerer Schulter-Transportpunkt',
    meridian: 'SI',
    element: 'fire',
    location: '2 cun lateral des Dornfortsatzes C7',
    depth: '0.5-1 cun',
    frequency: 440.1,
    harmonicFrequencies: calculateHarmonics(440.1),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Klärt Hitze'],
    indications: ['Husten', 'Asthma', 'Schulterschmerzen']
  },
  {
    id: 'SI16',
    nameChinese: 'Tianchuang',
    nameEnglish: 'Celestial Window',
    nameGerman: 'Himmlisches Fenster',
    meridian: 'SI',
    element: 'fire',
    location: 'Am Hinterrand des M. SCM, auf Höhe des Adamsapfels',
    depth: '0.5-1 cun',
    frequency: 447,
    harmonicFrequencies: calculateHarmonics(447),
    pointTypes: ['regular'],
    functions: ['Fördert Hören', 'Klärt Hitze'],
    indications: ['Tinnitus', 'Schwerhörigkeit', 'Halsschmerzen'],
    precautions: ['Vorsicht - Gefäße'],
    chakraCorrespondence: 'vishuddha'
  },
  {
    id: 'SI17',
    nameChinese: 'Tianrong',
    nameEnglish: 'Celestial Countenance',
    nameGerman: 'Himmlisches Antlitz',
    meridian: 'SI',
    element: 'fire',
    location: 'Hinter dem Unterkieferwinkel, am Vorderrand des M. SCM',
    depth: '0.5-1 cun',
    frequency: 453.9,
    harmonicFrequencies: calculateHarmonics(453.9),
    pointTypes: ['regular'],
    functions: ['Klärt Hitze', 'Lindert Schwellung'],
    indications: ['Halsschmerzen', 'Mandelentzündung', 'Tinnitus'],
    precautions: ['Vorsicht - Gefäße']
  },
  {
    id: 'SI18',
    nameChinese: 'Quanliao',
    nameEnglish: 'Cheekbone Hole',
    nameGerman: 'Jochbeinvertiefung',
    meridian: 'SI',
    element: 'fire',
    location: 'Direkt unter dem Jochbein, unter dem äußeren Augenwinkel',
    depth: '0.3-0.5 cun',
    frequency: 460.8,
    harmonicFrequencies: calculateHarmonics(460.8),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schwellung'],
    indications: ['Gesichtslähmung', 'Trigeminusneuralgie', 'Zahnschmerzen']
  },
  {
    id: 'SI19',
    nameChinese: 'Tinggong',
    nameEnglish: 'Auditory Palace',
    nameGerman: 'Hörpalast',
    meridian: 'SI',
    element: 'fire',
    location: 'Vor dem Tragus, bei geöffnetem Mund in der Vertiefung',
    depth: '0.5-1 cun',
    frequency: 467.7,
    harmonicFrequencies: calculateHarmonics(467.7),
    pointTypes: ['regular'],
    functions: ['Öffnet Ohren', 'Beruhigt Geist'],
    indications: ['Tinnitus', 'Schwerhörigkeit', 'Ohrenschmerzen', 'Kiefergelenksprobleme'],
    chakraCorrespondence: 'ajna'
  }
];
