/**
 * MILZMERIDIAN (SP) - 21 Punkte
 * Element: Erde (Yin), Maximalzeit: 9-11 Uhr
 * WHO Standard Acupuncture Point Locations (2008)
 */

import { AcupuncturePoint, calculateHarmonics } from '../meridianPointsDatabase';

export const SPLEEN_MERIDIAN: AcupuncturePoint[] = [
  {
    id: 'SP1',
    nameChinese: 'Yinbai',
    nameEnglish: 'Hidden White',
    nameGerman: 'Verborgenes Weiß',
    meridian: 'SP',
    element: 'earth',
    location: 'Am großen Zeh, 0.1 cun proximal des medialen Nagelwinkels',
    depth: '0.1 cun oder Blutenlassen',
    frequency: 256,
    harmonicFrequencies: calculateHarmonics(256),
    pointTypes: ['jing_well'],
    functions: ['Stärkt Milz', 'Stoppt Blutungen', 'Beruhigt Geist'],
    indications: ['Menorrhagie', 'Uterusblutung', 'Schlaflosigkeit', 'Alpträume'],
    chakraCorrespondence: 'muladhara'
  },
  {
    id: 'SP2',
    nameChinese: 'Dadu',
    nameEnglish: 'Great Metropolis',
    nameGerman: 'Große Stadt',
    meridian: 'SP',
    element: 'earth',
    location: 'Medial am großen Zeh, distal des 1. MTP-Gelenks',
    depth: '0.3-0.5 cun',
    frequency: 262.4,
    harmonicFrequencies: calculateHarmonics(262.4),
    pointTypes: ['ying_spring'],
    functions: ['Klärt Milz-Hitze', 'Reguliert Qi'],
    indications: ['Bauchschmerzen', 'Blähungen', 'Fieber ohne Schwitzen']
  },
  {
    id: 'SP3',
    nameChinese: 'Taibai',
    nameEnglish: 'Supreme White',
    nameGerman: 'Höchstes Weiß',
    meridian: 'SP',
    element: 'earth',
    location: 'Medial am Fuß, proximal des 1. MTP-Gelenks',
    depth: '0.5-1 cun',
    frequency: 272,
    harmonicFrequencies: calculateHarmonics(272),
    pointTypes: ['shu_stream', 'yuan_source'],
    functions: ['Stärkt Milz', 'Löst Feuchtigkeit', 'Harmonisiert Magen'],
    indications: ['Bauchschmerzen', 'Durchfall', 'Schwere der Glieder', 'Fußschmerzen'],
    chakraCorrespondence: 'manipura'
  },
  {
    id: 'SP4',
    nameChinese: 'Gongsun',
    nameEnglish: 'Yellow Emperor',
    nameGerman: 'Gelber Kaiser',
    meridian: 'SP',
    element: 'earth',
    location: 'Medial am Fuß, in der Vertiefung distal der Basis des 1. Metatarsale',
    depth: '0.5-1 cun',
    frequency: 288,
    harmonicFrequencies: calculateHarmonics(288),
    pointTypes: ['luo_connecting', 'confluent'],
    functions: ['Stärkt Milz', 'Reguliert Chong Mai', 'Harmonisiert Magen'],
    indications: ['Magenschmerzen', 'Übelkeit', 'Dysmenorrhoe', 'Herzschmerzen'],
    chakraCorrespondence: 'manipura'
  },
  {
    id: 'SP5',
    nameChinese: 'Shangqiu',
    nameEnglish: 'Shang Mound',
    nameGerman: 'Shang-Hügel',
    meridian: 'SP',
    element: 'earth',
    location: 'In der Vertiefung vor und unter dem medialen Malleolus',
    depth: '0.3-0.5 cun',
    frequency: 298.7,
    harmonicFrequencies: calculateHarmonics(298.7),
    pointTypes: ['jing_river'],
    functions: ['Stärkt Milz', 'Löst Feuchtigkeit'],
    indications: ['Knöchelschwellung', 'Bauchschmerzen', 'Verstopfung']
  },
  {
    id: 'SP6',
    nameChinese: 'Sanyinjiao',
    nameEnglish: 'Three Yin Intersection',
    nameGerman: 'Treffpunkt der drei Yin',
    meridian: 'SP',
    element: 'earth',
    location: '3 cun über dem medialen Malleolus, am Hinterrand der Tibia',
    depth: '1-1.5 cun',
    frequency: 307.2,
    harmonicFrequencies: calculateHarmonics(307.2),
    pointTypes: ['regular'],
    functions: ['Stärkt Milz', 'Nährt Leber und Nieren', 'Reguliert Menstruation'],
    indications: ['Gynäkologische Beschwerden', 'Verdauungsprobleme', 'Schlaflosigkeit', 'Schmerzen'],
    precautions: ['Kontraindiziert in der Schwangerschaft'],
    chakraCorrespondence: 'svadhisthana'
  },
  {
    id: 'SP7',
    nameChinese: 'Lougu',
    nameEnglish: 'Leaking Valley',
    nameGerman: 'Leckendes Tal',
    meridian: 'SP',
    element: 'earth',
    location: '6 cun über dem medialen Malleolus',
    depth: '1-1.5 cun',
    frequency: 312,
    harmonicFrequencies: calculateHarmonics(312),
    pointTypes: ['regular'],
    functions: ['Löst Feuchtigkeit', 'Reguliert Wasserwege'],
    indications: ['Bauchblähung', 'Ödeme', 'Knieschmerzen']
  },
  {
    id: 'SP8',
    nameChinese: 'Diji',
    nameEnglish: 'Earth Pivot',
    nameGerman: 'Erd-Drehpunkt',
    meridian: 'SP',
    element: 'earth',
    location: '3 cun unter SP9, am Hinterrand der Tibia',
    depth: '1-1.5 cun',
    frequency: 316.8,
    harmonicFrequencies: calculateHarmonics(316.8),
    pointTypes: ['xi_cleft'],
    functions: ['Reguliert Menstruation', 'Löst Blut-Stase'],
    indications: ['Dysmenorrhoe', 'Bauchschmerzen', 'Ödeme']
  },
  {
    id: 'SP9',
    nameChinese: 'Yinlingquan',
    nameEnglish: 'Yin Mound Spring',
    nameGerman: 'Yin-Hügel-Quelle',
    meridian: 'SP',
    element: 'earth',
    location: 'In der Vertiefung unter dem medialen Tibiakondylus',
    depth: '1-2 cun',
    frequency: 326.4,
    harmonicFrequencies: calculateHarmonics(326.4),
    pointTypes: ['he_sea'],
    functions: ['Löst Feuchtigkeit', 'Öffnet Wasserwege', 'Stärkt Milz'],
    indications: ['Ödeme', 'Harnprobleme', 'Knieschmerzen', 'Durchfall'],
    chakraCorrespondence: 'manipura'
  },
  {
    id: 'SP10',
    nameChinese: 'Xuehai',
    nameEnglish: 'Sea of Blood',
    nameGerman: 'Meer des Blutes',
    meridian: 'SP',
    element: 'earth',
    location: '2 cun über dem medialen Patellarand',
    depth: '1-1.5 cun',
    frequency: 332.8,
    harmonicFrequencies: calculateHarmonics(332.8),
    pointTypes: ['regular'],
    functions: ['Belebt Blut', 'Kühlt Blut', 'Reguliert Menstruation'],
    indications: ['Hauterkrankungen', 'Menstruationsstörungen', 'Knieschmerzen'],
    chakraCorrespondence: 'anahata'
  },
  {
    id: 'SP11',
    nameChinese: 'Jimen',
    nameEnglish: 'Winnowing Gate',
    nameGerman: 'Worfelndes Tor',
    meridian: 'SP',
    element: 'earth',
    location: '6 cun über SP10, am medialen Oberschenkel',
    depth: '0.5-1 cun',
    frequency: 339.2,
    harmonicFrequencies: calculateHarmonics(339.2),
    pointTypes: ['regular'],
    functions: ['Reguliert Wasserwege'],
    indications: ['Harnverhalt', 'Leistenschmerzen']
  },
  {
    id: 'SP12',
    nameChinese: 'Chongmen',
    nameEnglish: 'Rushing Gate',
    nameGerman: 'Drängendes Tor',
    meridian: 'SP',
    element: 'earth',
    location: '3.5 cun lateral der vorderen Mittellinie, am oberen Rand des Schambeins',
    depth: '0.5-1 cun',
    frequency: 345.6,
    harmonicFrequencies: calculateHarmonics(345.6),
    pointTypes: ['regular'],
    functions: ['Reguliert Qi', 'Lindert Schmerzen'],
    indications: ['Leistenschmerzen', 'Hernie']
  },
  {
    id: 'SP13',
    nameChinese: 'Fushe',
    nameEnglish: 'Bowel Abode',
    nameGerman: 'Darmwohnung',
    meridian: 'SP',
    element: 'earth',
    location: '4 cun lateral des Nabels, 0.7 cun über SP12',
    depth: '1-1.5 cun',
    frequency: 352,
    harmonicFrequencies: calculateHarmonics(352),
    pointTypes: ['regular'],
    functions: ['Reguliert Darm-Qi'],
    indications: ['Bauchschmerzen', 'Hernie']
  },
  {
    id: 'SP14',
    nameChinese: 'Fujie',
    nameEnglish: 'Abdomen Bind',
    nameGerman: 'Bauchband',
    meridian: 'SP',
    element: 'earth',
    location: '4 cun lateral des Nabels, 1.3 cun unter SP15',
    depth: '1-1.5 cun',
    frequency: 358.4,
    harmonicFrequencies: calculateHarmonics(358.4),
    pointTypes: ['regular'],
    functions: ['Reguliert Darm-Qi'],
    indications: ['Bauchschmerzen', 'Durchfall', 'Verstopfung']
  },
  {
    id: 'SP15',
    nameChinese: 'Daheng',
    nameEnglish: 'Great Horizontal',
    nameGerman: 'Große Horizontale',
    meridian: 'SP',
    element: 'earth',
    location: '4 cun lateral des Nabels',
    depth: '1-2 cun',
    frequency: 364.8,
    harmonicFrequencies: calculateHarmonics(364.8),
    pointTypes: ['regular'],
    functions: ['Stärkt Milz', 'Reguliert Darm-Qi'],
    indications: ['Bauchschmerzen', 'Durchfall', 'Verstopfung', 'Erschöpfung']
  },
  {
    id: 'SP16',
    nameChinese: 'Fuai',
    nameEnglish: 'Abdomen Sorrow',
    nameGerman: 'Bauchkummer',
    meridian: 'SP',
    element: 'earth',
    location: '3 cun über dem Nabel, 4 cun lateral der Mittellinie',
    depth: '1-1.5 cun',
    frequency: 371.2,
    harmonicFrequencies: calculateHarmonics(371.2),
    pointTypes: ['regular'],
    functions: ['Reguliert Darm-Qi'],
    indications: ['Bauchschmerzen', 'Verdauungsstörungen']
  },
  {
    id: 'SP17',
    nameChinese: 'Shidou',
    nameEnglish: 'Food Hole',
    nameGerman: 'Speisenhöhle',
    meridian: 'SP',
    element: 'earth',
    location: 'Im 5. ICR, 6 cun lateral der vorderen Mittellinie',
    depth: '0.5-0.8 cun schräg',
    frequency: 377.6,
    harmonicFrequencies: calculateHarmonics(377.6),
    pointTypes: ['regular'],
    functions: ['Reguliert Qi im Brustkorb'],
    indications: ['Brustschmerzen', 'Rippenschmerzen'],
    precautions: ['Nicht tief stechen - Pneumothorax-Risiko']
  },
  {
    id: 'SP18',
    nameChinese: 'Tianxi',
    nameEnglish: 'Celestial Ravine',
    nameGerman: 'Himmlische Schlucht',
    meridian: 'SP',
    element: 'earth',
    location: 'Im 4. ICR, 6 cun lateral der vorderen Mittellinie',
    depth: '0.5-0.8 cun schräg',
    frequency: 384,
    harmonicFrequencies: calculateHarmonics(384),
    pointTypes: ['regular'],
    functions: ['Reguliert Lungen-Qi', 'Fördert Laktation'],
    indications: ['Brustschmerzen', 'Husten', 'Mastitis'],
    precautions: ['Nicht tief stechen']
  },
  {
    id: 'SP19',
    nameChinese: 'Xiongxiang',
    nameEnglish: 'Chest Village',
    nameGerman: 'Brustdorf',
    meridian: 'SP',
    element: 'earth',
    location: 'Im 3. ICR, 6 cun lateral der vorderen Mittellinie',
    depth: '0.5-0.8 cun schräg',
    frequency: 390.4,
    harmonicFrequencies: calculateHarmonics(390.4),
    pointTypes: ['regular'],
    functions: ['Reguliert Qi im Brustkorb'],
    indications: ['Brustschmerzen', 'Rippenschmerzen'],
    precautions: ['Nicht tief stechen']
  },
  {
    id: 'SP20',
    nameChinese: 'Zhourong',
    nameEnglish: 'Encircling Glory',
    nameGerman: 'Umgebender Glanz',
    meridian: 'SP',
    element: 'earth',
    location: 'Im 2. ICR, 6 cun lateral der vorderen Mittellinie',
    depth: '0.5-0.8 cun schräg',
    frequency: 396.8,
    harmonicFrequencies: calculateHarmonics(396.8),
    pointTypes: ['regular'],
    functions: ['Reguliert Qi', 'Lindert Husten'],
    indications: ['Husten', 'Atemnot', 'Rippenschmerzen'],
    precautions: ['Nicht tief stechen']
  },
  {
    id: 'SP21',
    nameChinese: 'Dabao',
    nameEnglish: 'Great Embracement',
    nameGerman: 'Große Umarmung',
    meridian: 'SP',
    element: 'earth',
    location: 'Auf der mittleren Axillarlinie, im 6. ICR',
    depth: '0.5-0.8 cun schräg',
    frequency: 403.2,
    harmonicFrequencies: calculateHarmonics(403.2),
    pointTypes: ['luo_connecting'],
    functions: ['Reguliert Qi und Blut im ganzen Körper'],
    indications: ['Ganzkörperschmerzen', 'Schwäche der Extremitäten', 'Rippenschmerzen'],
    precautions: ['Nicht tief stechen'],
    chakraCorrespondence: 'anahata'
  }
];
