/**
 * DREIFACHER ERWÄRMER MERIDIAN (TE) - 23 Punkte
 * Element: Feuer (Yang), Maximalzeit: 21-23 Uhr
 * WHO Standard Acupuncture Point Locations (2008)
 */

import { AcupuncturePoint, calculateHarmonics } from '../meridianPointsDatabase';

export const TRIPLE_WARMER_MERIDIAN: AcupuncturePoint[] = [
  {
    id: 'TE1',
    nameChinese: 'Guanchong',
    nameEnglish: 'Rushing Pass',
    nameGerman: 'Drängende Passage',
    meridian: 'TE',
    element: 'fire',
    location: 'Am Ringfinger, 0.1 cun proximal des ulnaren Nagelwinkels',
    depth: '0.1 cun oder Blutenlassen',
    frequency: 343.5,
    harmonicFrequencies: calculateHarmonics(343.5),
    pointTypes: ['jing_well'],
    functions: ['Klärt Hitze', 'Belebt Bewusstsein'],
    indications: ['Kopfschmerzen', 'Halsschmerzen', 'Fieber', 'Konjunktivitis']
  },
  {
    id: 'TE2',
    nameChinese: 'Yemen',
    nameEnglish: 'Humor Gate',
    nameGerman: 'Flüssigkeitstor',
    meridian: 'TE',
    element: 'fire',
    location: 'Zwischen 4. und 5. Finger, proximal des Schwimmhautrandes',
    depth: '0.3-0.5 cun',
    frequency: 350.4,
    harmonicFrequencies: calculateHarmonics(350.4),
    pointTypes: ['ying_spring'],
    functions: ['Klärt Hitze', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Ohrenschmerzen', 'Halsschmerzen', 'Malaria']
  },
  {
    id: 'TE3',
    nameChinese: 'Zhongzhu',
    nameEnglish: 'Central Islet',
    nameGerman: 'Zentrale Insel',
    meridian: 'TE',
    element: 'fire',
    location: 'Auf dem Handrücken, zwischen 4. und 5. Metakarpale, proximal des MCP-Gelenks',
    depth: '0.5-1 cun',
    frequency: 357.3,
    harmonicFrequencies: calculateHarmonics(357.3),
    pointTypes: ['shu_stream'],
    functions: ['Zerstreut Wind-Hitze', 'Öffnet Ohren', 'Aktiviert Kanal'],
    indications: ['Tinnitus', 'Schwerhörigkeit', 'Kopfschmerzen', 'Handschmerzen']
  },
  {
    id: 'TE4',
    nameChinese: 'Yangchi',
    nameEnglish: 'Yang Pool',
    nameGerman: 'Yang-Teich',
    meridian: 'TE',
    element: 'fire',
    location: 'Auf dem Handrücken, in der Handgelenksfalte, ulnar der Strecksehnen',
    depth: '0.3-0.5 cun',
    frequency: 364.2,
    harmonicFrequencies: calculateHarmonics(364.2),
    pointTypes: ['yuan_source'],
    functions: ['Entspannt Sehnen', 'Stärkt Yuan-Qi'],
    indications: ['Handgelenkschmerzen', 'Schulterschmerzen', 'Diabetes']
  },
  {
    id: 'TE5',
    nameChinese: 'Waiguan',
    nameEnglish: 'Outer Pass',
    nameGerman: 'Äußere Grenze',
    meridian: 'TE',
    element: 'fire',
    location: '2 cun proximal der Handgelenksfalte, zwischen Radius und Ulna',
    depth: '0.5-1 cun',
    frequency: 371.1,
    harmonicFrequencies: calculateHarmonics(371.1),
    pointTypes: ['luo_connecting', 'confluent'],
    functions: ['Öffnet Yang Wei Mai', 'Zerstreut Wind-Hitze', 'Aktiviert Kanal'],
    indications: ['Erkältung', 'Kopfschmerzen', 'Tinnitus', 'Armschmerzen'],
    chakraCorrespondence: 'vishuddha'
  },
  {
    id: 'TE6',
    nameChinese: 'Zhigou',
    nameEnglish: 'Branch Ditch',
    nameGerman: 'Zweiggraben',
    meridian: 'TE',
    element: 'fire',
    location: '3 cun proximal der Handgelenksfalte, zwischen Radius und Ulna',
    depth: '0.5-1 cun',
    frequency: 378,
    harmonicFrequencies: calculateHarmonics(378),
    pointTypes: ['jing_river'],
    functions: ['Reguliert Qi', 'Klärt Hitze', 'Fördert Stuhlgang'],
    indications: ['Verstopfung', 'Rippenschmerzen', 'Schulterschmerzen']
  },
  {
    id: 'TE7',
    nameChinese: 'Huizong',
    nameEnglish: 'Convergence and Gathering',
    nameGerman: 'Zusammenkunft',
    meridian: 'TE',
    element: 'fire',
    location: '3 cun proximal der Handgelenksfalte, am radialen Rand der Ulna',
    depth: '0.5-1 cun',
    frequency: 384.9,
    harmonicFrequencies: calculateHarmonics(384.9),
    pointTypes: ['xi_cleft'],
    functions: ['Öffnet Ohren', 'Lindert Schmerzen'],
    indications: ['Schwerhörigkeit', 'Epilepsie', 'Armschmerzen']
  },
  {
    id: 'TE8',
    nameChinese: 'Sanyangluo',
    nameEnglish: 'Three Yang Connection',
    nameGerman: 'Drei-Yang-Verbindung',
    meridian: 'TE',
    element: 'fire',
    location: '4 cun proximal der Handgelenksfalte, zwischen Radius und Ulna',
    depth: '0.5-1 cun',
    frequency: 391.8,
    harmonicFrequencies: calculateHarmonics(391.8),
    pointTypes: ['regular'],
    functions: ['Öffnet Ohren', 'Aktiviert Kanal'],
    indications: ['Schwerhörigkeit', 'Zahnschmerzen', 'Armschmerzen']
  },
  {
    id: 'TE9',
    nameChinese: 'Sidu',
    nameEnglish: 'Four Rivers',
    nameGerman: 'Vier Flüsse',
    meridian: 'TE',
    element: 'fire',
    location: '5 cun distal des Olekranons, zwischen Radius und Ulna',
    depth: '0.5-1 cun',
    frequency: 398.7,
    harmonicFrequencies: calculateHarmonics(398.7),
    pointTypes: ['regular'],
    functions: ['Öffnet Ohren', 'Lindert Halsschmerzen'],
    indications: ['Schwerhörigkeit', 'Halsschmerzen', 'Zahnschmerzen']
  },
  {
    id: 'TE10',
    nameChinese: 'Tianjing',
    nameEnglish: 'Celestial Well',
    nameGerman: 'Himmlischer Brunnen',
    meridian: 'TE',
    element: 'fire',
    location: '1 cun über dem Olekranon, bei gebeugtem Ellenbogen',
    depth: '0.5-1 cun',
    frequency: 405.6,
    harmonicFrequencies: calculateHarmonics(405.6),
    pointTypes: ['he_sea'],
    functions: ['Transformiert Schleim', 'Zerstreut Stagnation', 'Beruhigt Geist'],
    indications: ['Ellenbogenschmerzen', 'Nackensteifigkeit', 'Skrofulose', 'Depression']
  },
  {
    id: 'TE11',
    nameChinese: 'Qinglengyuan',
    nameEnglish: 'Clear Cold Abyss',
    nameGerman: 'Klarer kalter Abgrund',
    meridian: 'TE',
    element: 'fire',
    location: '2 cun über dem Olekranon',
    depth: '0.5-1 cun',
    frequency: 412.5,
    harmonicFrequencies: calculateHarmonics(412.5),
    pointTypes: ['regular'],
    functions: ['Aktiviert Kanal', 'Lindert Schmerzen'],
    indications: ['Schulterschmerzen', 'Kopfschmerzen']
  },
  {
    id: 'TE12',
    nameChinese: 'Xiaoluo',
    nameEnglish: 'Dispersing Riverbed',
    nameGerman: 'Zerstreuendes Flussbett',
    meridian: 'TE',
    element: 'fire',
    location: 'Auf der Linie zwischen Olekranon und TE14, in der Mitte des Oberarms',
    depth: '0.5-1 cun',
    frequency: 419.4,
    harmonicFrequencies: calculateHarmonics(419.4),
    pointTypes: ['regular'],
    functions: ['Aktiviert Kanal', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Nackensteifigkeit', 'Armschmerzen']
  },
  {
    id: 'TE13',
    nameChinese: 'Naohui',
    nameEnglish: 'Upper Arm Convergence',
    nameGerman: 'Oberarm-Zusammenkunft',
    meridian: 'TE',
    element: 'fire',
    location: '3 cun unter TE14, am hinteren Rand des Deltoideus',
    depth: '0.5-1 cun',
    frequency: 426.3,
    harmonicFrequencies: calculateHarmonics(426.3),
    pointTypes: ['regular'],
    functions: ['Transformiert Schleim', 'Zerstreut Stagnation'],
    indications: ['Skrofulose', 'Armschmerzen']
  },
  {
    id: 'TE14',
    nameChinese: 'Jianliao',
    nameEnglish: 'Shoulder Bone Hole',
    nameGerman: 'Schulterknochen-Vertiefung',
    meridian: 'TE',
    element: 'fire',
    location: 'Posterior und inferior zum Akromion, bei abduziertem Arm',
    depth: '0.5-1 cun',
    frequency: 433.2,
    harmonicFrequencies: calculateHarmonics(433.2),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Aktiviert Kanal'],
    indications: ['Schulterschmerzen', 'Schultersteifigkeit', 'Armlähmung']
  },
  {
    id: 'TE15',
    nameChinese: 'Tianliao',
    nameEnglish: 'Celestial Bone Hole',
    nameGerman: 'Himmlische Knochenvertiefung',
    meridian: 'TE',
    element: 'fire',
    location: 'Auf der Mitte zwischen GB21 und SI13',
    depth: '0.5-1 cun',
    frequency: 440.1,
    harmonicFrequencies: calculateHarmonics(440.1),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Aktiviert Kanal'],
    indications: ['Nacken- und Schulterschmerzen', 'Armschmerzen']
  },
  {
    id: 'TE16',
    nameChinese: 'Tianyou',
    nameEnglish: 'Celestial Window',
    nameGerman: 'Himmlisches Fenster',
    meridian: 'TE',
    element: 'fire',
    location: 'Am Hinterrand des M. SCM, auf Höhe des Unterkieferwinkels',
    depth: '0.5-1 cun',
    frequency: 447,
    harmonicFrequencies: calculateHarmonics(447),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Erhellt Sinne'],
    indications: ['Gesichtsschwellung', 'Sehstörungen', 'Schwerhörigkeit'],
    precautions: ['Vorsicht - Gefäße']
  },
  {
    id: 'TE17',
    nameChinese: 'Yifeng',
    nameEnglish: 'Wind Screen',
    nameGerman: 'Windschirm',
    meridian: 'TE',
    element: 'fire',
    location: 'Hinter dem Ohrläppchen, zwischen Processus mastoideus und Unterkieferast',
    depth: '0.5-1 cun',
    frequency: 453.9,
    harmonicFrequencies: calculateHarmonics(453.9),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Öffnet Ohren', 'Lindert Schmerzen'],
    indications: ['Tinnitus', 'Schwerhörigkeit', 'Gesichtslähmung', 'Ohrenschmerzen'],
    chakraCorrespondence: 'ajna'
  },
  {
    id: 'TE18',
    nameChinese: 'Chimai',
    nameEnglish: 'Spasm Vessel',
    nameGerman: 'Krampfgefäß',
    meridian: 'TE',
    element: 'fire',
    location: 'In der Mitte des Processus mastoideus, an der Haargrenze',
    depth: '0.3-0.5 cun schräg oder Blutenlassen',
    frequency: 460.8,
    harmonicFrequencies: calculateHarmonics(460.8),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Tinnitus', 'Kinderkrämpfe']
  },
  {
    id: 'TE19',
    nameChinese: 'Luxi',
    nameEnglish: 'Skull Rest',
    nameGerman: 'Schädelruhe',
    meridian: 'TE',
    element: 'fire',
    location: 'Am Hinterrand des Ohres, auf Höhe der Ohrmuschelmitte',
    depth: '0.3-0.5 cun schräg',
    frequency: 467.7,
    harmonicFrequencies: calculateHarmonics(467.7),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schmerzen'],
    indications: ['Kopfschmerzen', 'Tinnitus', 'Ohrenschmerzen']
  },
  {
    id: 'TE20',
    nameChinese: 'Jiaosun',
    nameEnglish: 'Minute Angle',
    nameGerman: 'Winziger Winkel',
    meridian: 'TE',
    element: 'fire',
    location: 'An der Ohrspitze, an der Haargrenze',
    depth: '0.3-0.5 cun schräg',
    frequency: 474.6,
    harmonicFrequencies: calculateHarmonics(474.6),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Lindert Schwellung'],
    indications: ['Augenrötung', 'Zahnschmerzen', 'Ohrenschwellung']
  },
  {
    id: 'TE21',
    nameChinese: 'Ermen',
    nameEnglish: 'Ear Gate',
    nameGerman: 'Ohrentor',
    meridian: 'TE',
    element: 'fire',
    location: 'Vor der Incisura supratragica, bei geöffnetem Mund',
    depth: '0.5-1 cun',
    frequency: 481.5,
    harmonicFrequencies: calculateHarmonics(481.5),
    pointTypes: ['regular'],
    functions: ['Öffnet Ohren', 'Zerstreut Wind-Hitze'],
    indications: ['Tinnitus', 'Schwerhörigkeit', 'Ohrenschmerzen', 'Zahnschmerzen'],
    chakraCorrespondence: 'ajna'
  },
  {
    id: 'TE22',
    nameChinese: 'Heliao',
    nameEnglish: 'Harmony Bone Hole',
    nameGerman: 'Harmonie-Knochenvertiefung',
    meridian: 'TE',
    element: 'fire',
    location: 'An der Haargrenze, hinter der A. temporalis superficialis',
    depth: '0.3-0.5 cun schräg',
    frequency: 488.4,
    harmonicFrequencies: calculateHarmonics(488.4),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Aktiviert Kanal'],
    indications: ['Kopfschmerzen', 'Tinnitus', 'Kiefergelenksprobleme'],
    precautions: ['Vorsicht - A. temporalis']
  },
  {
    id: 'TE23',
    nameChinese: 'Sizhukong',
    nameEnglish: 'Silk Bamboo Hole',
    nameGerman: 'Seidenbambus-Vertiefung',
    meridian: 'TE',
    element: 'fire',
    location: 'Am lateralen Ende der Augenbraue, in der Vertiefung',
    depth: '0.3-0.5 cun schräg',
    frequency: 495.3,
    harmonicFrequencies: calculateHarmonics(495.3),
    pointTypes: ['regular'],
    functions: ['Zerstreut Wind', 'Erhellt Augen'],
    indications: ['Kopfschmerzen', 'Augenschmerzen', 'Gesichtslähmung', 'Epilepsie'],
    chakraCorrespondence: 'ajna'
  }
];
